import test from 'node:test';
import assert from 'node:assert';

import { NahuatlParser } from '../src/index.js';

const parser = new NahuatlParser();

test('Morphologically ambiguous words', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("imeuh")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"i","details":{"morpheme":"i","type":"prefix","role":"possessive","person":"third","number":"singular","english":"his/her/its","used_with":"noun"}},{"morpheme":"me","details":{"morpheme":"me","type":"noun_stem","english":"mageuy","countable":true,"animate":false}},{"morpheme":"uh","details":{"morpheme":"uh","type":"suffix","category":"possessive"}}],"englishTranslation":"(it is) his/her/its mageuy"},{"morphemes":[{"morpheme":"im","details":{"morpheme":"im","type":"prefix","role":"possessive","person":"third","number":"plural","english":"their","used_with":"noun"}},{"morpheme":"e","details":{"morpheme":"e","type":"noun_stem","english":"bean","countable":true,"animate":false}},{"morpheme":"uh","details":{"morpheme":"uh","type":"suffix","category":"possessive"}}],"englishTranslation":"(it is) their bean"}]}`, "imeuh");
});

test('Invariable words', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("ahmo")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ahmo","details":{"morpheme":"ahmo","type":"particle","english":"no, not"}}],"englishTranslation":"no, not"}]}`, "particle");
  assert.strictEqual(JSON.stringify(parser.analyze("tlein")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"tlein","details":{"morpheme":"tlein","type":"interrogative","english":"what"}}],"englishTranslation":"what"}]}`, "interrogative");
  assert.strictEqual(JSON.stringify(parser.analyze("nican")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"nican","details":{"morpheme":"nican","type":"adverb","english":"here"}}],"englishTranslation":"here"}]}`, "adverb");
});

test('Singular absolutive suffixes', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("coyotl")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"coyo","details":{"morpheme":"coyo","type":"noun_stem","english":"coyote","countable":true,"animate":true}},{"morpheme":"tl","details":{"morpheme":"tl","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"(it is a) coyote"}]}`, "-tl");
  assert.strictEqual(JSON.stringify(parser.analyze("molli")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"mol","details":{"morpheme":"mol","type":"noun_stem","english":"sauce","countable":true,"animate":false}},{"morpheme":"li","details":{"morpheme":"li","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"(it is a) sauce"}]}`, "-lli");
  assert.strictEqual(JSON.stringify(parser.analyze("cactli")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cac","details":{"morpheme":"cac","type":"noun_stem","english":"sandal","countable":true,"animate":false}},{"morpheme":"tli","details":{"morpheme":"tli","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"(it is a) sandal"}]}`, "-tli");
  assert.strictEqual(JSON.stringify(parser.analyze("cacahuatl")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cacahua","details":{"morpheme":"cacahua","type":"noun_stem","english":"cacao","countable":false,"animate":false}},{"morpheme":"tl","details":{"morpheme":"tl","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"(it is) cacao"}]}`, "uncountable");
});

test('Plural absolutive suffixes', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("ichcame")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ichca","details":{"morpheme":"ichca","type":"noun_stem","english":"sheep","english_plural":"sheep","countable":true,"animate":true}},{"morpheme":"me","details":{"morpheme":"me","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) sheep"}]}`, "-me");   
  assert.strictEqual(JSON.stringify(parser.analyze("cihuameh")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cihua","details":{"morpheme":"cihua","type":"noun_stem","english":"woman","english_plural":"women","countable":true,"animate":true}},{"morpheme":"meh","details":{"morpheme":"meh","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) women"}]}`, "-meh");
  assert.strictEqual(JSON.stringify(parser.analyze("oquichtin")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"oquich","details":{"morpheme":"oquich","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"tin","details":{"morpheme":"tin","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) men"}]}`, "-tin");
  assert.strictEqual(JSON.stringify(parser.analyze("cihuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cihua","details":{"morpheme":"cihua","type":"noun_stem","english":"woman","english_plural":"women","countable":true,"animate":true}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) women"}]}`, "-h");
});

test('Predicate nouns', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("nitlacatl")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ni","details":{"morpheme":"ni","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"tlaca","details":{"morpheme":"tlaca","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"tl","details":{"morpheme":"tl","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"I am a man"}]}`, "ni- -absolutive");
  assert.strictEqual(JSON.stringify(parser.analyze("titlacatl")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"tlaca","details":{"morpheme":"tlaca","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"tl","details":{"morpheme":"tl","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"you (sg) are a man"}]}`, "ti- -absolutive");
  assert.strictEqual(JSON.stringify(parser.analyze("titlacah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"tlaca","details":{"morpheme":"tlaca","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"we are men"}]}`, "ti- noun");
  assert.strictEqual(JSON.stringify(parser.analyze("antlacah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"an","details":{"morpheme":"an","type":"prefix","role":"subject","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"tlaca","details":{"morpheme":"tlaca","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"you (pl) are men"}]}`, "an- noun");
  assert.strictEqual(JSON.stringify(parser.analyze("tlacah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"tlaca","details":{"morpheme":"tlaca","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) men"}]}`, "an- noun");
});

test('Singular possessive prefixes and suffixes', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("nomol")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"no","details":{"morpheme":"no","type":"prefix","role":"possessive","person":"first","number":"singular","english":"my","used_with":"noun"}},{"morpheme":"mol","details":{"morpheme":"mol","type":"noun_stem","english":"sauce","countable":true,"animate":false}}],"englishTranslation":"(it is) my sauce"}]}`, "no-");
  assert.strictEqual(JSON.stringify(parser.analyze("mocihuauh")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"mo","details":{"morpheme":"mo","type":"prefix","role":"possessive","person":"second","number":"singular","english":"your (sg)","used_with":"noun"}},{"morpheme":"cihua","details":{"morpheme":"cihua","type":"noun_stem","english":"woman","english_plural":"women","countable":true,"animate":true}},{"morpheme":"uh","details":{"morpheme":"uh","type":"suffix","category":"possessive"}}],"englishTranslation":"(it is) your (sg) woman"}]}`, "mo- -uh");
  assert.strictEqual(JSON.stringify(parser.analyze("ichichiuh")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"i","details":{"morpheme":"i","type":"prefix","role":"possessive","person":"third","number":"singular","english":"his/her/its","used_with":"noun"}},{"morpheme":"chichi","details":{"morpheme":"chichi","type":"noun_stem","english":"dog","countable":true,"animate":true}},{"morpheme":"uh","details":{"morpheme":"uh","type":"suffix","category":"possessive"}}],"englishTranslation":"(it is) his/her/its dog"}]}`, "i- -uh");
  assert.strictEqual(JSON.stringify(parser.analyze("notlacahuan")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"no","details":{"morpheme":"no","type":"prefix","role":"possessive","person":"first","number":"singular","english":"my","used_with":"noun"}},{"morpheme":"tlaca","details":{"morpheme":"tlaca","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"huan","details":{"morpheme":"huan","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) my men"}]}`, "no- -huan");  
  assert.strictEqual(JSON.stringify(parser.analyze("mocihuahuan")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"mo","details":{"morpheme":"mo","type":"prefix","role":"possessive","person":"second","number":"singular","english":"your (sg)","used_with":"noun"}},{"morpheme":"cihua","details":{"morpheme":"cihua","type":"noun_stem","english":"woman","english_plural":"women","countable":true,"animate":true}},{"morpheme":"huan","details":{"morpheme":"huan","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) your (sg) women"}]}`, "mo- -huan");
  assert.strictEqual(JSON.stringify(parser.analyze("ichichihuan")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"i","details":{"morpheme":"i","type":"prefix","role":"possessive","person":"third","number":"singular","english":"his/her/its","used_with":"noun"}},{"morpheme":"chichi","details":{"morpheme":"chichi","type":"noun_stem","english":"dog","countable":true,"animate":true}},{"morpheme":"huan","details":{"morpheme":"huan","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) his/her/its dogs"}]}`, "i- -huan");
});


test('Plural possessive prefixes and suffixes', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("tomol")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"to","details":{"morpheme":"to","type":"prefix","role":"possessive","person":"first","number":"plural","english":"our","used_with":"noun"}},{"morpheme":"mol","details":{"morpheme":"mol","type":"noun_stem","english":"sauce","countable":true,"animate":false}}],"englishTranslation":"(it is) our sauce"}]}`, "to-");
  assert.strictEqual(JSON.stringify(parser.analyze("amocihuauh")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"amo","details":{"morpheme":"amo","type":"prefix","role":"possessive","person":"second","number":"plural","english":"your (pl)","used_with":"noun"}},{"morpheme":"cihua","details":{"morpheme":"cihua","type":"noun_stem","english":"woman","english_plural":"women","countable":true,"animate":true}},{"morpheme":"uh","details":{"morpheme":"uh","type":"suffix","category":"possessive"}}],"englishTranslation":"(it is) your (pl) woman"}]}`, "amo- -uh");
  assert.strictEqual(JSON.stringify(parser.analyze("imchichiuh")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"im","details":{"morpheme":"im","type":"prefix","role":"possessive","person":"third","number":"plural","english":"their","used_with":"noun"}},{"morpheme":"chichi","details":{"morpheme":"chichi","type":"noun_stem","english":"dog","countable":true,"animate":true}},{"morpheme":"uh","details":{"morpheme":"uh","type":"suffix","category":"possessive"}}],"englishTranslation":"(it is) their dog"}]}`, "im- -uh");
  assert.strictEqual(JSON.stringify(parser.analyze("totlacahuan")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"to","details":{"morpheme":"to","type":"prefix","role":"possessive","person":"first","number":"plural","english":"our","used_with":"noun"}},{"morpheme":"tlaca","details":{"morpheme":"tlaca","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"huan","details":{"morpheme":"huan","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) our men"}]}`, "to- -huan");
  assert.strictEqual(JSON.stringify(parser.analyze("amocihuahuan")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"amo","details":{"morpheme":"amo","type":"prefix","role":"possessive","person":"second","number":"plural","english":"your (pl)","used_with":"noun"}},{"morpheme":"cihua","details":{"morpheme":"cihua","type":"noun_stem","english":"woman","english_plural":"women","countable":true,"animate":true}},{"morpheme":"huan","details":{"morpheme":"huan","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) your (pl) women"}]}`, "amo- -huan");
  assert.strictEqual(JSON.stringify(parser.analyze("imchichihuan")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"im","details":{"morpheme":"im","type":"prefix","role":"possessive","person":"third","number":"plural","english":"their","used_with":"noun"}},{"morpheme":"chichi","details":{"morpheme":"chichi","type":"noun_stem","english":"dog","countable":true,"animate":true}},{"morpheme":"huan","details":{"morpheme":"huan","type":"suffix","category":"plural"}}],"englishTranslation":"(they are) their dogs"}]}`, "im- -huan");
});

test('Third person singular verbs', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("cahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"he/she/it leaves"}]}`, "no object prefix"); // find intransitive example
  assert.strictEqual(JSON.stringify(parser.analyze("nechcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"nech","details":{"morpheme":"nech","type":"prefix","role":"object","person":"first","number":"singular","english":"me"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"he/she/it leaves me"}]}`, "nech");
  assert.strictEqual(JSON.stringify(parser.analyze("mitzcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"mitz","details":{"morpheme":"mitz","type":"prefix","role":"object","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"he/she/it leaves you (sg)"}]}`, "mitz");
  assert.strictEqual(JSON.stringify(parser.analyze("quicahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"qui","details":{"morpheme":"qui","type":"prefix","role":"object","person":"third","number":"singular","english":"him/her/it"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"he/she/it leaves him/her/it"}]}`, "qui");
  assert.strictEqual(JSON.stringify(parser.analyze("techcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"tech","details":{"morpheme":"tech","type":"prefix","role":"object","person":"first","number":"plural","english":"us"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"he/she/it leaves us"}]}`, "mitz");
  assert.strictEqual(JSON.stringify(parser.analyze("amechcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"amech","details":{"morpheme":"amech","type":"prefix","role":"object","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"he/she/it leaves you (pl)"}]}`, "mitz");
  assert.strictEqual(JSON.stringify(parser.analyze("quincahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"quin","details":{"morpheme":"quin","type":"prefix","role":"object","person":"third","number":"plural","english":"them"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"he/she/it leaves them"}]}`, "mitz");
});


test('Third person plural verbs', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("cahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"they leave"}]}`, "no object prefix"); // find intransitive example
  assert.strictEqual(JSON.stringify(parser.analyze("nechcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"nech","details":{"morpheme":"nech","type":"prefix","role":"object","person":"first","number":"singular","english":"me"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"they leave me"}]}`, "nech");
  assert.strictEqual(JSON.stringify(parser.analyze("mitzcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"mitz","details":{"morpheme":"mitz","type":"prefix","role":"object","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"they leave you (sg)"}]}`, "mitz");
  assert.strictEqual(JSON.stringify(parser.analyze("quicahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"qui","details":{"morpheme":"qui","type":"prefix","role":"object","person":"third","number":"singular","english":"him/her/it"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"they leave him/her/it"}]}`, "qui");
  assert.strictEqual(JSON.stringify(parser.analyze("techcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"tech","details":{"morpheme":"tech","type":"prefix","role":"object","person":"first","number":"plural","english":"us"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"they leave us"}]}`, "mitz");
  assert.strictEqual(JSON.stringify(parser.analyze("amechcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"amech","details":{"morpheme":"amech","type":"prefix","role":"object","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"they leave you (pl)"}]}`, "mitz");
  assert.strictEqual(JSON.stringify(parser.analyze("quincahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"quin","details":{"morpheme":"quin","type":"prefix","role":"object","person":"third","number":"plural","english":"them"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"they leave them"}]}`, "mitz");
});

test('Second person singular verbs', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("ticahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"we leave"},{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"you (sg) leave"}]}`, "no object prefix"); // find intransitive example
  assert.strictEqual(JSON.stringify(parser.analyze("tinechcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"nech","details":{"morpheme":"nech","type":"prefix","role":"object","person":"first","number":"singular","english":"me"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"we leave me"},{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"nech","details":{"morpheme":"nech","type":"prefix","role":"object","person":"first","number":"singular","english":"me"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"you (sg) leave me"}]}`, "nech");
  assert.strictEqual(JSON.stringify(parser.analyze("ticcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"c","details":{"morpheme":"c","type":"prefix","role":"object","person":"third","number":"singular","english":"him/her/it"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"we leave him/her/it"},{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"c","details":{"morpheme":"c","type":"prefix","role":"object","person":"third","number":"singular","english":"him/her/it"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"you (sg) leave him/her/it"}]}`, "c");
  assert.strictEqual(JSON.stringify(parser.analyze("titechcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"tech","details":{"morpheme":"tech","type":"prefix","role":"object","person":"first","number":"plural","english":"us"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"we leave us"},{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"tech","details":{"morpheme":"tech","type":"prefix","role":"object","person":"first","number":"plural","english":"us"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"you (sg) leave us"}]}`, "tech");
  assert.strictEqual(JSON.stringify(parser.analyze("tiquincahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"quin","details":{"morpheme":"quin","type":"prefix","role":"object","person":"third","number":"plural","english":"them"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"we leave them"},{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"quin","details":{"morpheme":"quin","type":"prefix","role":"object","person":"third","number":"plural","english":"them"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"you (sg) leave them"}]}`, "quin");
});

test('Second person plural verbs', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("ancahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"an","details":{"morpheme":"an","type":"prefix","role":"subject","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"you (pl) leave"}]}`, "no object prefix"); // find intransitive example
  assert.strictEqual(JSON.stringify(parser.analyze("annechcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"an","details":{"morpheme":"an","type":"prefix","role":"subject","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"nech","details":{"morpheme":"nech","type":"prefix","role":"object","person":"first","number":"singular","english":"me"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"you (pl) leave me"}]}`, "nech"); 
  assert.strictEqual(JSON.stringify(parser.analyze("anccahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"an","details":{"morpheme":"an","type":"prefix","role":"subject","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"c","details":{"morpheme":"c","type":"prefix","role":"object","person":"third","number":"singular","english":"him/her/it"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"you (pl) leave him/her/it"}]}`, "c");
  assert.strictEqual(JSON.stringify(parser.analyze("antechcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"an","details":{"morpheme":"an","type":"prefix","role":"subject","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"tech","details":{"morpheme":"tech","type":"prefix","role":"object","person":"first","number":"plural","english":"us"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"you (pl) leave us"}]}`, "tech");
  assert.strictEqual(JSON.stringify(parser.analyze("anquincahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"an","details":{"morpheme":"an","type":"prefix","role":"subject","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"quin","details":{"morpheme":"quin","type":"prefix","role":"object","person":"third","number":"plural","english":"them"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"you (pl) leave them"}]}`, "quin");
});

test('First person singular verbs', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("nicahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ni","details":{"morpheme":"ni","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"I leave"}]}`, "no object prefix"); // find intransitive example
  assert.strictEqual(JSON.stringify(parser.analyze("nimitzcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ni","details":{"morpheme":"ni","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"mitz","details":{"morpheme":"mitz","type":"prefix","role":"object","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"I leave you (sg)"}]}`, "mitz");
  assert.strictEqual(JSON.stringify(parser.analyze("niccahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ni","details":{"morpheme":"ni","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"c","details":{"morpheme":"c","type":"prefix","role":"object","person":"third","number":"singular","english":"him/her/it"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"I leave him/her/it"}]}`, "c");
  assert.strictEqual(JSON.stringify(parser.analyze("namechcahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"n","details":{"morpheme":"n","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"amech","details":{"morpheme":"amech","type":"prefix","role":"object","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"I leave you (pl)"}]}`, "amech");
  assert.strictEqual(JSON.stringify(parser.analyze("niquincahua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ni","details":{"morpheme":"ni","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"quin","details":{"morpheme":"quin","type":"prefix","role":"object","person":"third","number":"plural","english":"them"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}}],"englishTranslation":"I leave them"}]}`, "quin");
});

test('First person plural verbs', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("ticahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"we leave"}]}`, "no object prefix"); // find intransitive example
  assert.strictEqual(JSON.stringify(parser.analyze("timitzcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"mitz","details":{"morpheme":"mitz","type":"prefix","role":"object","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"we leave you (sg)"}]}`, "no object prefix"); 
  assert.strictEqual(JSON.stringify(parser.analyze("ticcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"c","details":{"morpheme":"c","type":"prefix","role":"object","person":"third","number":"singular","english":"him/her/it"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"we leave him/her/it"}]}`, "c");
  assert.strictEqual(JSON.stringify(parser.analyze("tamechcahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"amech","details":{"morpheme":"amech","type":"prefix","role":"object","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"we leave you (pl)"}]}`, "amech");
  assert.strictEqual(JSON.stringify(parser.analyze("tiquincahuah")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"quin","details":{"morpheme":"quin","type":"prefix","role":"object","person":"third","number":"plural","english":"them"}},{"morpheme":"cahua","details":{"morpheme":"cahua","type":"verb_stem","english":"leave","past":"left","pp":"left"}},{"morpheme":"h","details":{"morpheme":"h","type":"suffix","category":"plural"}}],"englishTranslation":"we leave them"}]}`, "quin");
});

test('Compound words', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("cacahuacomitl")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cacahua","details":{"morpheme":"cacahua","type":"noun_stem","english":"cacao","countable":false,"animate":false}},{"morpheme":"comi","details":{"morpheme":"comi","type":"noun_stem","english":"pot","countable":true,"animate":false}},{"morpheme":"tl","details":{"morpheme":"tl","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"(it is a) cacao-pot"}]}`, "noun + noun + suffix");
  assert.strictEqual(JSON.stringify(parser.analyze("cuauhtemoc")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cuauh","details":{"morpheme":"cuauh","type":"noun_stem","english":"eagle","countable":true,"animate":true}},{"morpheme":"temoc","details":{"morpheme":"temoc","type":"verb_stem","english":"descend"}}],"englishTranslation":"he/she/it descends like an eagle"}]}`, "noun_stem + verb_stem");
  assert.strictEqual(JSON.stringify(parser.analyze("noxochicihuatl")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"no","details":{"morpheme":"no","type":"prefix","role":"possessive","person":"first","number":"singular","english":"my","used_with":"noun"}},{"morpheme":"xochi","details":{"morpheme":"xochi","type":"noun_stem","english":"flower","countable":true,"animate":false}},{"morpheme":"cihua","details":{"morpheme":"cihua","type":"noun_stem","english":"woman","english_plural":"women","countable":true,"animate":true}},{"morpheme":"tl","details":{"morpheme":"tl","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"(it is) my flower-woman"}]}`, "prefix + noun + noun + suffix");
});


test('-lli participles', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("pitzalli")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"pitza","details":{"morpheme":"pitza","type":"verb_stem","english":"blow","past":"blew","pp":"blown"}},{"morpheme":"lli","details":{"morpheme":"lli","type":"suffix","category":"participle","nominalizing":true,"countable":true}}],"englishTranslation":"(it is) blown"}]}`, "-lli");
  assert.strictEqual(JSON.stringify(parser.analyze("tlaittalli")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"tla","details":{"morpheme":"tla","type":"prefix","role":"object","implies_something":true}},{"morpheme":"itta","details":{"morpheme":"itta","type":"verb_stem","english":"see","past":"saw","pp":"seen"}},{"morpheme":"lli","details":{"morpheme":"lli","type":"suffix","category":"participle","nominalizing":true,"countable":true}}],"englishTranslation":"(it is) something seen"}]}`, "tla- -lli"); // I know this one doesn't have proper elision yet
  assert.strictEqual(JSON.stringify(parser.analyze("notlacualli")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"no","details":{"morpheme":"no","type":"prefix","role":"possessive","person":"first","number":"singular","english":"my","used_with":"noun"}},{"morpheme":"tla","details":{"morpheme":"tla","type":"prefix","role":"object","implies_something":true}},{"morpheme":"cua","details":{"morpheme":"cua","type":"verb_stem","english":"eat","past":"ate","pp":"eaten"}},{"morpheme":"lli","details":{"morpheme":"lli","type":"suffix","category":"participle","nominalizing":true,"countable":true}}],"englishTranslation":"(it is) my something eaten"}]}`, "no- tla- -lli");
});

test('-ni habitual', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("tlahtolmatini")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"tlahtol","details":{"morpheme":"tlahtol","type":"noun_stem","english":"word","countable":true,"animate":false}},{"morpheme":"mati","details":{"morpheme":"mati","type":"verb_stem","english":"know","past":"knew","pp":"known"}},{"morpheme":"ni","details":{"morpheme":"ni","type":"suffix","category":"habitual","english_suffix":"er","nominalizing":true,"countable":true}}],"englishTranslation":"(it is a) word-knower"}]}`, "-ni habitual");
});

test('Reflexive verbs', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("ninoitta")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ni","details":{"morpheme":"ni","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"no","details":{"morpheme":"no","type":"prefix","role":"reflexive","person":"first","number":"singular","english":"myself","used_with":"verb"}},{"morpheme":"itta","details":{"morpheme":"itta","type":"verb_stem","english":"see","past":"saw","pp":"seen"}}],"englishTranslation":"I see myself"}]}`, "ni- no-");
  assert.strictEqual(JSON.stringify(parser.analyze("timoitta")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"mo","details":{"morpheme":"mo","type":"prefix","role":"reflexive","person":"second","number":"singular","english":"yourself (sg)","used_with":"verb"}},{"morpheme":"itta","details":{"morpheme":"itta","type":"verb_stem","english":"see","past":"saw","pp":"seen"}}],"englishTranslation":"you (sg) see yourself (sg)"}]}`, "ti- mo-");
  assert.strictEqual(JSON.stringify(parser.analyze("moitta")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"mo","details":{"morpheme":"mo","type":"prefix","role":"reflexive","person":"third","number":"singular","english":"him/her/itself","used_with":"verb"}},{"morpheme":"itta","details":{"morpheme":"itta","type":"verb_stem","english":"see","past":"saw","pp":"seen"}}],"englishTranslation":"he/she/it sees him/her/itself"}]}`, "mo-");
  assert.strictEqual(JSON.stringify(parser.analyze("titoitta")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ti","details":{"morpheme":"ti","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"to","details":{"morpheme":"to","type":"prefix","role":"reflexive","person":"first","number":"plural","english":"ourselves","used_with":"verb"}},{"morpheme":"itta","details":{"morpheme":"itta","type":"verb_stem","english":"see","past":"saw","pp":"seen"}}],"englishTranslation":"we see ourselves"}]}`, "ti- to-");
  assert.strictEqual(JSON.stringify(parser.analyze("ammoitta")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"am","details":{"morpheme":"am","type":"prefix","role":"subject","person":"second","number":"plural","english":"you (pl)"}},{"morpheme":"mo","details":{"morpheme":"mo","type":"prefix","role":"reflexive","person":"second","number":"plural","english":"yourselves","used_with":"verb"}},{"morpheme":"itta","details":{"morpheme":"itta","type":"verb_stem","english":"see","past":"saw","pp":"seen"}}],"englishTranslation":"you (pl) see yourselves"}]}`, "am- mo-");
});
