import test from 'node:test';
import assert from 'node:assert';

import { modernToClassical, classicalToModern } from '../src/helper.js';

test('Modern to classical orthography conversion', () => {
  assert.strictEqual(modernToClassical('axkanah'), 'axcanah', 'axcanah');
  assert.strictEqual(modernToClassical('iwkin'), 'yuhquin', 'yuhquin');
  assert.strictEqual(modernToClassical('itstok'), 'itztoc', 'itztoc');
  assert.strictEqual(modernToClassical('senka'), 'cenca', 'cenca');
  assert.strictEqual(modernToClassical('kemah'), 'quemah', 'quemah');
  assert.strictEqual(modernToClassical('kena'), 'quena', 'quena');
  assert.strictEqual(modernToClassical('kwix'), 'cuix', 'cuix');
  assert.strictEqual(modernToClassical('aw'), 'auh', 'auh');
  assert.strictEqual(modernToClassical('wan'), 'huan', 'huan');
  assert.strictEqual(modernToClassical('san'), 'zan', 'zan');
  assert.strictEqual(modernToClassical('akin'), 'aquin', 'aquin');
  assert.strictEqual(modernToClassical('akkiya'), 'acquiya', 'acquiya');
  assert.strictEqual(modernToClassical('keniwki'), 'queniuhqui', 'queniuhqui');
  assert.strictEqual(modernToClassical('ak'), 'ac', 'ac');
  assert.strictEqual(modernToClassical('mits'), 'mitz', 'mitz');
  assert.strictEqual(modernToClassical('wetska'), 'huetzca', 'huetzca');
  assert.strictEqual(modernToClassical('tlaketsa'), 'tlaquetza', 'tlaquetza');
  assert.strictEqual(modernToClassical('kweponi'), 'cueponi', 'cueponi');
  assert.strictEqual(modernToClassical('tsatsi'), 'tzatzi', 'tzatzi');
  assert.strictEqual(modernToClassical('kixtia'), 'quixtia', 'quixtia');
  assert.strictEqual(modernToClassical('tikchiwa'), 'ticchihua', 'ticchihua');
  assert.strictEqual(modernToClassical('poliwi'), 'polihui', 'polihui');
  assert.strictEqual(modernToClassical('pawax'), 'pahuax', 'pahuax');
  assert.strictEqual(modernToClassical('kweya'), 'cueya', 'cueya');
  assert.strictEqual(modernToClassical('okichpil'), 'oquichpil', 'oquichpil');
  assert.strictEqual(modernToClassical('tiyankis'), 'tiyanquiz', 'tiyanquiz');
  assert.strictEqual(modernToClassical('listli'), 'liztli', 'liztli');
  assert.strictEqual(modernToClassical('tsintli'), 'tzintli', 'tzintli');
  assert.strictEqual(modernToClassical('tlakwa'), 'tlacua', 'tlacua');
  assert.strictEqual(modernToClassical('nekwtli'), 'necuhtli', 'necuhtli');
  assert.strictEqual(modernToClassical('nikkaki'), 'niccaqui', 'niccaqui');
  assert.strictEqual(modernToClassical('nikkowa'), 'niccohua', 'niccohua');
  assert.strictEqual(modernToClassical('miston'), 'mizton', 'mizton');
  assert.strictEqual(modernToClassical('tlaskamati'), 'tlazcamati', 'tlazcamati');
  assert.strictEqual(modernToClassical('nimitstlahpalos'), 'nimitztlahpaloz', 'nimitztlahpaloz');
});

test('Classical to modern orthography conversion', () => {
  assert.strictEqual(classicalToModern('axcanah'), 'axkanah', 'axkanah');
  assert.strictEqual(classicalToModern('yuhquin'), 'iwkin', 'yuhkin');
  assert.strictEqual(classicalToModern('itztoc'), 'itstok', 'itstok');
  assert.strictEqual(classicalToModern('cenca'), 'senka', 'senka');
  assert.strictEqual(classicalToModern('quemah'), 'kemah', 'kemah');
  assert.strictEqual(classicalToModern('quena'), 'kena', 'kena');
  assert.strictEqual(classicalToModern('cuix'), 'kwix', 'kwix');
  assert.strictEqual(classicalToModern('auh'), 'aw', 'aw');
  assert.strictEqual(classicalToModern('huan'), 'wan', 'wan');
  assert.strictEqual(classicalToModern('zan'), 'san', 'san');
  assert.strictEqual(classicalToModern('aquin'), 'akin', 'akin');
  assert.strictEqual(classicalToModern('acquiya'), 'akkiya', 'akkiya');
  assert.strictEqual(classicalToModern('queniuhqui'), 'keniwki', 'keniwki');
  assert.strictEqual(classicalToModern('ac'), 'ak', 'ak');
  assert.strictEqual(classicalToModern('mitz'), 'mits', 'mits');
  assert.strictEqual(classicalToModern('huetzca'), 'wetska', 'wetska');
  assert.strictEqual(classicalToModern('tlaquetza'), 'tlaketsa', 'tlaketsa');
  assert.strictEqual(classicalToModern('cueponi'), 'kweponi', 'kweponi');
  assert.strictEqual(classicalToModern('tzatzi'), 'tsatsi', 'tsatsi');
  assert.strictEqual(classicalToModern('quixtia'), 'kixtia', 'kixtia');
  assert.strictEqual(classicalToModern('ticchihua'), 'tikchiwa', 'tikchiwa');
  assert.strictEqual(classicalToModern('polihui'), 'poliwi', 'poliwi');
  assert.strictEqual(classicalToModern('pahuax'), 'pawax', 'pawax');
  assert.strictEqual(classicalToModern('cueya'), 'kweya', 'kweya');
  assert.strictEqual(classicalToModern('oquichpil'), 'okichpil', 'okichpil');
  assert.strictEqual(classicalToModern('tiyanquiz'), 'tiyankis', 'tiyankis');
  assert.strictEqual(classicalToModern('liztli'), 'listli', 'listli');
  assert.strictEqual(classicalToModern('tzintli'), 'tsintli', 'tsintli');
  assert.strictEqual(classicalToModern('tlacua'), 'tlakwa', 'tlakwa');
  assert.strictEqual(classicalToModern('necuhtli'), 'nekwtli', 'nekwtli');
  assert.strictEqual(classicalToModern('niccaqui'), 'nikkaki', 'nikkaki');
  assert.strictEqual(classicalToModern('niccohua'), 'nikkowa', 'nikkowa');
  assert.strictEqual(classicalToModern('mizton'), 'miston', 'miston');
  assert.strictEqual(classicalToModern('tlazcamati'), 'tlaskamati', 'tlaskamati');
  assert.strictEqual(classicalToModern('nimitztlahpaloz'), 'nimitstlahpalos', 'nimitstlahpalos');
});

test('Launey to modern orthography conversion', () => {
  assert.strictEqual(classicalToModern('teuctli'), 'tekwtli', 'tekwtli');
  assert.strictEqual(classicalToModern('èecatl'), 'ehekatl', 'ehekatl');
  assert.strictEqual(classicalToModern('tlacuâ'), 'tlakwah', 'tlakwah');
});
