import test from 'node:test';
import assert from 'node:assert';

import { NahuatlParser } from '../src/index.js';

const parser = new NahuatlParser();

test('Vocabulary', () => {
  assert.strictEqual(JSON.stringify(parser.analyze("tamolnamacac")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"amol","details":{"morpheme":"amol","type":"noun_stem","english":"soap","countable":true,"animate":false}},{"morpheme":"namacac","details":{"morpheme":"namacac","type":"noun_stem","english":"seller","countable":true,"animate":true,"absolutive_suffix":false}}],"englishTranslation":"we are a soap-seller"},{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"amol","details":{"morpheme":"amol","type":"noun_stem","english":"soap","countable":true,"animate":false}},{"morpheme":"namacac","details":{"morpheme":"namacac","type":"noun_stem","english":"seller","countable":true,"animate":true,"absolutive_suffix":false}}],"englishTranslation":"you (sg) are a soap-seller"},{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"possessive","person":"first","number":"plural","english":"our","used_with":"noun"}},{"morpheme":"amol","details":{"morpheme":"amol","type":"noun_stem","english":"soap","countable":true,"animate":false}},{"morpheme":"namacac","details":{"morpheme":"namacac","type":"noun_stem","english":"seller","countable":true,"animate":true,"absolutive_suffix":false}}],"englishTranslation":"(it is) our soap-seller"}]}`, "tamolnacac");
  assert.strictEqual(JSON.stringify(parser.analyze("tamol")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"subject","person":"first","number":"plural","english":"we"}},{"morpheme":"amol","details":{"morpheme":"amol","type":"noun_stem","english":"soap","countable":true,"animate":false}}],"englishTranslation":"we are a soap"},{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"amol","details":{"morpheme":"amol","type":"noun_stem","english":"soap","countable":true,"animate":false}}],"englishTranslation":"you (sg) are a soap"},{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"possessive","person":"first","number":"plural","english":"our","used_with":"noun"}},{"morpheme":"amol","details":{"morpheme":"amol","type":"noun_stem","english":"soap","countable":true,"animate":false}}],"englishTranslation":"(it is) our soap"}]}`, "tamol");
  assert.strictEqual(JSON.stringify(parser.analyze("nenamacac")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"n","details":{"morpheme":"n","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"e","details":{"morpheme":"e","type":"noun_stem","english":"bean","countable":true,"animate":false}},{"morpheme":"namacac","details":{"morpheme":"namacac","type":"noun_stem","english":"seller","countable":true,"animate":true,"absolutive_suffix":false}}],"englishTranslation":"I am a bean-seller"},{"morphemes":[{"morpheme":"n","details":{"morpheme":"n","type":"prefix","role":"possessive","person":"first","number":"singular","english":"my","used_with":"noun"}},{"morpheme":"e","details":{"morpheme":"e","type":"noun_stem","english":"bean","countable":true,"animate":false}},{"morpheme":"namacac","details":{"morpheme":"namacac","type":"noun_stem","english":"seller","countable":true,"animate":true,"absolutive_suffix":false}}],"englishTranslation":"(it is) my bean-seller"}]}`, "nenamacac");
  assert.strictEqual(JSON.stringify(parser.analyze("mepahuax")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"m","details":{"morpheme":"m","type":"prefix","role":"possessive","person":"second","number":"singular","english":"your (sg)","used_with":"noun"}},{"morpheme":"e","details":{"morpheme":"e","type":"noun_stem","english":"bean","countable":true,"animate":false}},{"morpheme":"pahuax","details":{"morpheme":"pahuax","type":"noun_stem","english":"cooked","countable":true,"animate":false}}],"englishTranslation":"(it is) your (sg) bean-cooked"}]}`, "mepahuax");
  assert.strictEqual(JSON.stringify(parser.analyze("toquichtli")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"subject","person":"second","number":"singular","english":"you (sg)"}},{"morpheme":"oquich","details":{"morpheme":"oquich","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"tli","details":{"morpheme":"tli","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"you (sg) are a man"},{"morphemes":[{"morpheme":"t","details":{"morpheme":"t","type":"prefix","role":"possessive","person":"first","number":"plural","english":"our","used_with":"noun"}},{"morpheme":"oquich","details":{"morpheme":"oquich","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"tli","details":{"morpheme":"tli","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"(it is) our man"}]}`, "toquichtli");
  assert.strictEqual(JSON.stringify(parser.analyze("amoquichtequiuh")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"am","details":{"morpheme":"am","type":"prefix","role":"possessive","person":"second","number":"plural","english":"your (pl)","used_with":"noun"}},{"morpheme":"oquich","details":{"morpheme":"oquich","type":"noun_stem","english":"man","english_plural":"men","countable":true,"animate":true}},{"morpheme":"tequi","details":{"morpheme":"tequi","type":"noun_stem","english":"work","countable":false,"animate":false}},{"morpheme":"uh","details":{"morpheme":"uh","type":"suffix","category":"possessive"}}],"englishTranslation":"(it is) your (pl) man-work"}]}`, "amoquichtequiuh");
  assert.strictEqual(JSON.stringify(parser.analyze("nichpochtli")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"n","details":{"morpheme":"n","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"ichpoch","details":{"morpheme":"ichpoch","type":"noun_stem","english":"girl","countable":true,"animate":true}},{"morpheme":"tli","details":{"morpheme":"tli","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"I am a girl"}]}`, "nichpochtli");
  assert.strictEqual(JSON.stringify(parser.analyze("iacal")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"i","details":{"morpheme":"i","type":"prefix","role":"possessive","person":"third","number":"singular","english":"his/her/its","used_with":"noun"}},{"morpheme":"acal","details":{"morpheme":"acal","type":"noun_stem","english":"boat","countable":true,"animate":false}}],"englishTranslation":"(it is) his/her/its boat"}]}`, "");
  assert.strictEqual(JSON.stringify(parser.analyze("tlaittalli")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"tla","details":{"morpheme":"tla","type":"prefix","role":"object","implies_something":true}},{"morpheme":"itta","details":{"morpheme":"itta","type":"verb_stem","english":"see","past":"saw","pp":"seen"}},{"morpheme":"lli","details":{"morpheme":"lli","type":"suffix","category":"participle","nominalizing":true,"countable":true}}],"englishTranslation":"(it is) something seen"}]}`, "tlaittalli");
  assert.strictEqual(JSON.stringify(parser.analyze("tocihuaxochitl")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"to","details":{"morpheme":"to","type":"prefix","role":"possessive","person":"first","number":"plural","english":"our","used_with":"noun"}},{"morpheme":"cihua","details":{"morpheme":"cihua","type":"noun_stem","english":"woman","english_plural":"women","countable":true,"animate":true}},{"morpheme":"xochi","details":{"morpheme":"xochi","type":"noun_stem","english":"flower","countable":true,"animate":false}},{"morpheme":"tl","details":{"morpheme":"tl","type":"suffix","category":"absolutive","nominalizing":true,"countable":true}}],"englishTranslation":"(it is) our woman-flower"}]}`, "tocihuaxochitl");
  assert.strictEqual(JSON.stringify(parser.analyze("cua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"cua","details":{"morpheme":"cua","type":"verb_stem","english":"eat","past":"ate","pp":"eaten"}}],"englishTranslation":"he/she/it eats"}]}`, "cua");
  assert.strictEqual(JSON.stringify(parser.analyze("tlacua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"tla","details":{"morpheme":"tla","type":"prefix","role":"object","implies_something":true}},{"morpheme":"cua","details":{"morpheme":"cua","type":"verb_stem","english":"eat","past":"ate","pp":"eaten"}}],"englishTranslation":"he/she/it eats something"}]}`, "tlacua");
  assert.strictEqual(JSON.stringify(parser.analyze("nicua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ni","details":{"morpheme":"ni","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"cua","details":{"morpheme":"cua","type":"verb_stem","english":"eat","past":"ate","pp":"eaten"}}],"englishTranslation":"I eat"}]}`, "nicua");
  assert.strictEqual(JSON.stringify(parser.analyze("nitlacua")), `{"success":true,"parsings":[{"morphemes":[{"morpheme":"ni","details":{"morpheme":"ni","type":"prefix","role":"subject","person":"first","number":"singular","english":"I"}},{"morpheme":"tla","details":{"morpheme":"tla","type":"prefix","role":"object","implies_something":true}},{"morpheme":"cua","details":{"morpheme":"cua","type":"verb_stem","english":"eat","past":"ate","pp":"eaten"}}],"englishTranslation":"I eat something"}]}`, "nitlacua");
});
