export const nounStems = [
  { morpheme: 'acal', type: 'noun_stem', english: 'boat', countable: true, animate: false },
  { morpheme: 'ahuaca', type: 'noun_stem', english: 'avocado', countable: true, animate: false },
  { morpheme: 'ahui', type: 'noun_stem', english: 'aunt', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'altepe', type: 'noun_stem', english: 'city', countable: true, animate: false },
  { morpheme: 'ama', type: 'noun_stem', english: 'paper', countable: false, animate: false },
  { morpheme: 'amanal', type: 'noun_stem', english: 'pond', countable: true, animate: false },
  { morpheme: 'amol', type: 'noun_stem', english: 'soap', countable: true, animate: false },
  { morpheme: 'amox', type: 'noun_stem', english: 'book', countable: true, animate: false },
  { morpheme: 'ayo', type: 'noun_stem', english: 'turtle', countable: true, animate: true },
  { morpheme: 'cac', type: 'noun_stem', english: 'sandal', countable: true, animate: false },
  { morpheme: 'cacahua', type: 'noun_stem', english: 'cacao', countable: false, animate: false },
  { morpheme: 'cacaoh', type: 'noun_stem', english: 'cacao', countable: false, animate: false, absolutiveSuffix: false },
  { morpheme: 'cahuayoh', type: 'noun_stem', english: 'horse', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'cal', type: 'noun_stem', english: 'house', countable: true, animate: false },
  { morpheme: 'camoh', type: 'noun_stem', english: 'yam', countable: true, animate: false },
  { morpheme: 'cen', type: 'noun_stem', english: 'one', countable: false, animate: false },
  { morpheme: 'chahuiz', type: 'noun_stem', english: 'fungus', countable: false, animate: false },
  { morpheme: 'chan', type: 'noun_stem', english: 'house', countable: true, animate: false },
  { morpheme: 'chichi', type: 'noun_stem', english: 'dog', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'chil', type: 'noun_stem', english: 'chili', countable: true, animate: false },
  { morpheme: 'cicitlal', type: 'noun_stem', english: 'star', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'cihua', type: 'noun_stem', english: 'woman', englishPlural: 'women', countable: true, animate: true },
  { morpheme: 'cihuapil', type: 'noun_stem', english: 'girl', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'citlalin', type: 'noun_stem', english: 'star', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'coa', type: 'noun_stem', english: 'serpent', countable: true, animate: true },
  { morpheme: 'cocohua', type: 'noun_stem', english: 'snake', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'cocone', type: 'noun_stem', english: 'child', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'cocoyo', type: 'noun_stem', english: 'coyote', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'cohua', type: 'noun_stem', english: 'snake', countable: true, animate: true },
  { morpheme: 'comi', type: 'noun_stem', english: 'pot', countable: true, animate: false },
  { morpheme: 'cone', type: 'noun_stem', english: 'child', countable: true, animate: true },
  { morpheme: 'cotomi', type: 'noun_stem', english: 'shirt', countable: true, animate: false },
  { morpheme: 'coyo', type: 'noun_stem', english: 'coyote', countable: true, animate: true },
  { morpheme: 'cuahui', type: 'noun_stem', english: 'tree', countable: true, animate: false },
  { morpheme: 'cuapuertah', type: 'noun_stem', english: 'door', countable: true, animate: false, absolutiveSuffix: false },
  { morpheme: 'cuatochin', type: 'noun_stem', english: 'rabbit', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'cuauh', type: 'noun_stem', english: 'eagle', countable: true, animate: true },
  { morpheme: 'cuei', type: 'noun_stem', english: 'skirt', countable: true, animate: false },
  { morpheme: 'cueya', type: 'noun_stem', english: 'frog', englishPlural: 'frogs', countable: true, animate: true },
  { morpheme: 'e', type: 'noun_stem', english: 'bean', countable: true, animate: false },
  { morpheme: 'eheca', type: 'noun_stem', english: 'wind', countable: false, animate: false },
  { morpheme: 'huacax', type: 'noun_stem', english: 'cow', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'ichca', type: 'noun_stem', english: 'sheep', englishPlural: 'sheep', countable: true, animate: true },
  { morpheme: 'ichpoca', type: 'noun_stem', english: 'teen girl', countable: true, animate: true },
  { morpheme: 'ichpoch', type: 'noun_stem', english: 'girl', countable: true, animate: true },
  { morpheme: 'icni', type: 'noun_stem', english: 'sibling', countable: true, animate: true },
  { morpheme: 'icniuh', type: 'noun_stem', english: 'friend', countable: true, animate: true },
  { morpheme: 'ixtiyol', type: 'noun_stem', english: 'eye', countable: true, animate: true },
  { morpheme: 'ixxayac', type: 'noun_stem', english: 'face', countable: true, animate: true },
  { morpheme: 'macehual', type: 'noun_stem', english: 'person', englishPlural: 'people', countable: true, animate: true },
  { morpheme: 'maxochi', type: 'noun_stem', english: 'gay man', englishPlural: 'gay men', countable: true, animate: true },
  { morpheme: 'me', type: 'noun_stem', english: 'mageuy', countable: true, animate: false },
  { morpheme: 'meca', type: 'noun_stem', english: 'rope', countable: true, animate: false },
  { morpheme: 'mexihca', type: 'noun_stem', english: 'Mexica person', englishPlural: 'Mexica people', countable: true, animate: true },
  { morpheme: 'mich', type: 'noun_stem', english: 'fish', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'michi', type: 'noun_stem', english: 'fish', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'michin', type: 'noun_stem', english: 'fish', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'mizton', type: 'noun_stem', english: 'cat', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'mol', type: 'noun_stem', english: 'sauce', countable: true, animate: false },
  { morpheme: 'mocauhqui', type: 'noun_stem', english: 'married person', englishPlural: 'married people', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'namacac', type: 'noun_stem', english: 'seller', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'nan', type: 'noun_stem', english: 'mother', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'nanan', type: 'noun_stem', english: 'mother', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'nacaz', type: 'noun_stem', english: 'ear', countable: true, animate: true },
  { morpheme: 'necuh', type: 'noun_stem', english: 'honey', countable: false, animate: false },
  { morpheme: 'nemilis', type: 'noun_stem', english: 'life', countable: true, animate: true },
  { morpheme: 'ocuili', type: 'noun_stem', english: 'worm', countable: true, animate: true },
  { morpheme: 'ocuilin', type: 'noun_stem', english: 'worm', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'oh', type: 'noun_stem', english: 'path', countable: true, animate: false },
  { morpheme: 'on', type: 'noun_stem', english: 'two', countable: false, animate: false },
  { morpheme: 'oquich', type: 'noun_stem', english: 'man', englishPlural: 'men', countable: true, animate: true },
  { morpheme: 'oquichpil', type: 'noun_stem', english: 'boy', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'otomi', type: 'noun_stem', english: 'Otomi person', englishPlural: 'Otomi people', countable: true, animate: true },
  { morpheme: 'pah', type: 'noun_stem', english: 'medicine', countable: false, animate: false },
  { morpheme: 'pahuax', type: 'noun_stem', english: 'cooked', countable: true, animate: false },
  { morpheme: 'pami', type: 'noun_stem', english: 'banner', countable: true, animate: false },
  { morpheme: 'pantalon', type: 'noun_stem', english: 'pants', countable: false, animate: false, absolutiveSuffix: false },
  { morpheme: 'papalo', type: 'noun_stem', english: 'butterfly', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'patox', type: 'noun_stem', english: 'duck', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'pil', type: 'noun_stem', english: 'noble', countable: true, animate: true },
  { morpheme: 'pipil', type: 'noun_stem', english: 'noble', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'pitzo', type: 'noun_stem', english: 'pig', countable: true, animate: true },
  { morpheme: 'piyo', type: 'noun_stem', english: 'chicken', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'quetzal', type: 'noun_stem', english: 'quetzal feather', countable: true, animate: false },
  { morpheme: 'tamal', type: 'noun_stem', english: 'tamal', englishPlural: 'tamales', countable: true, animate: false },
  { morpheme: 'tatah', type: 'noun_stem', english: 'father', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'te', type: 'noun_stem', english: 'stone', countable: true, animate: false },
  { morpheme: 'tecac', type: 'noun_stem', english: 'shoe', countable: true, animate: false },
  { morpheme: 'tecciz', type: 'noun_stem', english: 'egg', countable: true, animate: false },
  { morpheme: 'tecuh', type: 'noun_stem', english: 'lord', countable: true, animate: true },
  { morpheme: 'tecoh', type: 'noun_stem', english: 'lord', countable: true, animate: true },
  { morpheme: 'telpoca', type: 'noun_stem', english: 'teen boy', countable: true, animate: true },
  { morpheme: 'teo', type: 'noun_stem', english: 'god', countable: true, animate: true },
  { morpheme: 'tepe', type: 'noun_stem', english: 'hill', countable: true, animate: true },
  { morpheme: 'tepoz', type: 'noun_stem', english: 'metal', countable: false, animate: false },
  { morpheme: 'tequi', type: 'noun_stem', english: 'work', countable: false, animate: false },
  { morpheme: 'tetepe', type: 'noun_stem', english: 'hill', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'tiyanquiz', type: 'noun_stem', english: 'market', countable: true, animate: false },
  { morpheme: 'tlaca', type: 'noun_stem', english: 'man', englishPlural: 'men', countable: true, animate: true },
  { morpheme: 'tlahtol', type: 'noun_stem', english: 'word', countable: true, animate: false },
  { morpheme: 'tlal', type: 'noun_stem', english: 'land', countable: false, animate: false },
  { morpheme: 'tlaltipac', type: 'noun_stem', english: 'world', countable: true, animate: false },
  { morpheme: 'tlatzotzon', type: 'noun_stem', english: 'music', countable: false, animate: false },
  { morpheme: 'tlayi', type: 'noun_stem', english: 'uncle', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'toca', type: 'noun_stem', english: 'spider', countable: true, animate: true },
  { morpheme: 'tocai', type: 'noun_stem', english: 'name', countable: true, animate: false },
  { morpheme: 'toch', type: 'noun_stem', english: 'rabbit', countable: true, animate: true },
  { morpheme: 'toma', type: 'noun_stem', english: 'tomato', englishPlural: 'tomatoes', countable: true, animate: false },
  { morpheme: 'tomin', type: 'noun_stem', english: 'coin', countable: true, animate: false, absolutiveSuffix: false },
  { morpheme: 'tonatiuh', type: 'noun_stem', english: 'sun', countable: true, animate: false, absolutiveSuffix: false },
  { morpheme: 'toroh', type: 'noun_stem', english: 'bull', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'toto', type: 'noun_stem', english: 'bird', countable: true, animate: true },
  { morpheme: 'totoch', type: 'noun_stem', english: 'rabbit', countable: true, animate: true, irregularPlural: true },
  { morpheme: 'tzapo', type: 'noun_stem', english: 'sapote', countable: true, animate: false },
  { morpheme: 'tzoncal', type: 'noun_stem', english: 'hair', countable: false, animate: false },
  { morpheme: 'tzontecon', type: 'noun_stem', english: 'head', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'xochi', type: 'noun_stem', english: 'flower', countable: true, animate: false },
  { morpheme: 'yacatzol', type: 'noun_stem', english: 'nose', countable: true, animate: true },
  { morpheme: 'yollo', type: 'noun_stem', english: 'heart', countable: true, animate: true },
  { morpheme: 'zayolin', type: 'noun_stem', english: 'fly', countable: true, animate: true, absolutiveSuffix: false },
];
