export const particles = [
  { morpheme: 'achtopa', type: 'particle', english: 'first' },
  { morpheme: 'ahmo', type: 'particle', english: 'no, not' },
  { morpheme: 'amo', type: 'particle', english: 'no, not' },
  { morpheme: 'auh', type: 'particle', english: 'and then' },
  { morpheme: 'axcanah', type: 'particle', english: 'no' },
  { morpheme: 'ca', type: 'particle', english: 'truly, indeed' },
  { morpheme: 'ce', type: 'particle', english: 'a, one' },
  { morpheme: 'cenca', type: 'particle', english: 'very' },
  { morpheme: 'huan', type: 'particle', english: 'and' },
  { morpheme: 'in', type: 'particle', english: 'the (definite article)' },
  { morpheme: 'inihqueh', type: 'particle', english: 'these, those' },
  { morpheme: 'inin', type: 'particle', english: 'this' },
  { morpheme: 'inon', type: 'particle', english: 'that' },
  { morpheme: 'itztoc', type: 'particle', english: "it's here" },
  { morpheme: 'no', type: 'particle', english: 'also' },
  { morpheme: 'oc', type: 'particle', english: 'still, yet' },
  { morpheme: 'peh', type: 'particle', english: 'then, so' },
  { morpheme: 'quemah', type: 'particle', english: 'yes' },
  { morpheme: 'quemeh', type: 'particle', english: 'like' },
  { morpheme: 'quena', type: 'particle', english: 'yes' },
  { morpheme: 'san', type: 'particle', english: 'only, just' },
  { morpheme: 'tel', type: 'particle', english: 'but' },
  { morpheme: 'yuhquin', type: 'particle', english: 'like this' },
  { morpheme: 'zan', type: 'particle', english: 'only, just' },
];
