export const prefixes = [
  { morpheme: 'ah', type: 'prefix', role: 'negation', english: 'not' },
  { morpheme: 'am', type: 'prefix', role: 'subject', person: 'second', number: 'plural', english: 'you (pl)' },
  { morpheme: 'an', type: 'prefix', role: 'subject', person: 'second', number: 'plural', english: 'you (pl)' },
  { morpheme: 'in', type: 'prefix', role: 'subject', person: 'second', number: 'plural', english: 'you (pl)' },
  { morpheme: 'n', type: 'prefix', role: 'subject', person: 'first', number: 'singular', english: 'I' },
  { morpheme: 'ni', type: 'prefix', role: 'subject', person: 'first', number: 'singular', english: 'I' },
  { morpheme: 't', type: 'prefix', role: 'subject', person: 'first', number: 'plural', english: 'we' },
  { morpheme: 't', type: 'prefix', role: 'subject', person: 'second', number: 'singular', english: 'you (sg)' },
  { morpheme: 'ti', type: 'prefix', role: 'subject', person: 'first', number: 'plural', english: 'we' },
  { morpheme: 'ti', type: 'prefix', role: 'subject', person: 'second', number: 'singular', english: 'you (sg)' },
  { morpheme: 'amech', type: 'prefix', role: 'object', person: 'second', number: 'plural', english: 'you (pl)' },
  { morpheme: 'c', type: 'prefix', role: 'object', person: 'third', number: 'singular', english: 'him/her/it' },
  { morpheme: 'mitz', type: 'prefix', role: 'object', person: 'second', number: 'singular', english: 'you (sg)' },
  { morpheme: 'nech', type: 'prefix', role: 'object', person: 'first', number: 'singular', english: 'me' },
  { morpheme: 'pil', type: 'prefix', role: 'sacred_diminutive', english: 'small' },
  { morpheme: 'qu', type: 'prefix', role: 'object', person: 'third', number: 'singular', english: 'him/her/it' },
  { morpheme: 'qui', type: 'prefix', role: 'object', person: 'third', number: 'singular', english: 'him/her/it' },
  { morpheme: 'quim', type: 'prefix', role: 'object', person: 'third', number: 'plural', english: 'them' },
  { morpheme: 'quin', type: 'prefix', role: 'object', person: 'third', number: 'plural', english: 'them' },
  { morpheme: 'te', type: 'prefix', role: 'object', impliesSomeone: true },
  { morpheme: 'tech', type: 'prefix', role: 'object', person: 'first', number: 'plural', english: 'us' },
  { morpheme: 'tla', type: 'prefix', role: 'object', impliesSomething: true },
  { morpheme: 'x', type: 'prefix', category: 'imperative', english: 'you (sg/pl)', replacesSubject: true },
  { morpheme: 'xi', type: 'prefix', category: 'imperative', english: 'you (sg/pl)', replacesSubject: true },
  { morpheme: 'am', type: 'prefix', role: 'possessive', person: 'second', number: 'plural', english: 'your (pl)', usedWith: 'noun' },
  { morpheme: 'amo', type: 'prefix', role: 'possessive', person: 'second', number: 'plural', english: 'your (pl)', usedWith: 'noun' },
  { morpheme: 'i', type: 'prefix', role: 'possessive', person: 'third', number: 'singular', english: 'his/her/its', usedWith: 'noun' },
  { morpheme: 'im', type: 'prefix', role: 'possessive', person: 'third', number: 'plural', english: 'their', usedWith: 'noun' },
  { morpheme: 'in', type: 'prefix', role: 'possessive', person: 'third', number: 'plural', english: 'their', usedWith: 'noun' },
  { morpheme: 'inin', type: 'prefix', role: 'possessive', person: 'third', number: 'plural', english: 'their', usedWith: 'noun' },
  { morpheme: 'inmo', type: 'prefix', role: 'possessive', person: 'second', number: 'plural', english: 'your (pl)', usedWith: 'noun' },
  { morpheme: 'm', type: 'prefix', role: 'possessive', person: 'second', number: 'singular', english: 'your (sg)', usedWith: 'noun' },
  { morpheme: 'm', type: 'prefix', role: 'reflexive', person: 'second', number: 'singular', english: 'yourself (sg)', usedWith: 'verb' },
  { morpheme: 'mo', type: 'prefix', role: 'possessive', person: 'second', number: 'singular', english: 'your (sg)', usedWith: 'noun' },
  { morpheme: 'mo', type: 'prefix', role: 'reflexive', person: 'second', number: 'singular', english: 'yourself (sg)', usedWith: 'verb' },
  { morpheme: 'mo', type: 'prefix', role: 'reflexive', person: 'second', number: 'plural', english: 'yourselves', usedWith: 'verb' },
  { morpheme: 'mo', type: 'prefix', role: 'reflexive', person: 'third', number: 'singular', english: 'him/her/itself', usedWith: 'verb' },
  { morpheme: 'n', type: 'prefix', role: 'possessive', person: 'first', number: 'singular', english: 'my', usedWith: 'noun' },
  { morpheme: 'n', type: 'prefix', role: 'reflexive', person: 'first', number: 'singular', english: 'myself', usedWith: 'verb' },
  { morpheme: 'no', type: 'prefix', role: 'possessive', person: 'first', number: 'singular', english: 'my', usedWith: 'noun' },
  { morpheme: 'no', type: 'prefix', role: 'reflexive', person: 'first', number: 'singular', english: 'myself', usedWith: 'verb' },
  { morpheme: 't', type: 'prefix', role: 'possessive', person: 'first', number: 'plural', english: 'our', usedWith: 'noun' },
  { morpheme: 't', type: 'prefix', role: 'reflexive', person: 'first', number: 'plural', english: 'ourselves', usedWith: 'verb' },
  { morpheme: 'to', type: 'prefix', role: 'possessive', person: 'first', number: 'plural', english: 'our', usedWith: 'noun' },
  { morpheme: 'to', type: 'prefix', role: 'reflexive', person: 'first', number: 'plural', english: 'ourselves', usedWith: 'verb' },
];
