export const suffixes = [
  { morpheme: 'ah', type: 'suffix', category: 'unspecified', englishPrefix: 'some' },
  { morpheme: 'ca', type: 'suffix', category: 'locative', englishSuffix: ' place' },
  { morpheme: 'can', type: 'suffix', category: 'locative', englishPrefix: 'place of' },
  { morpheme: 'can', type: 'suffix', category: 'plural' },
  { morpheme: 'co', type: 'suffix', category: 'locative', englishPrefix: 'place on ' },
  { morpheme: 'eh', type: 'suffix', category: 'possessive', englishSuffix: ' owner' },
  { morpheme: 'h', type: 'suffix', category: 'plural' },
  { morpheme: 'hua', type: 'suffix', category: 'possessive', englishSuffix: ' owner of ' },
  { morpheme: 'huan', type: 'suffix', category: 'plural' },
  { morpheme: 'huia', type: 'suffix', category: 'applicative', englishSuffix: ' for ' },
  { morpheme: 'ic', type: 'suffix', category: 'instrumental', englishSuffix: ' with ' },
  { morpheme: 'li', type: 'suffix', category: 'absolutive', nominalizing: true, countable: true },
  { morpheme: 'lia', type: 'suffix', category: 'applicative', englishSuffix: ' for ' },
  { morpheme: 'liztli', type: 'suffix', category: 'nominalizer', englishSuffix: 'ing', nominalizing: true, countable: true },
  { morpheme: 'lli', type: 'suffix', category: 'participle', nominalizing: true, countable: true },
  { morpheme: 'me', type: 'suffix', category: 'plural' },
  { morpheme: 'meh', type: 'suffix', category: 'plural' },
  { morpheme: 'ni', type: 'suffix', category: 'habitual', englishSuffix: 'er', nominalizing: true, countable: true },
  { morpheme: 'oa', type: 'suffix', category: 'transitivizer', englishSuffix: ' to (do something)' },
  { morpheme: 'pan', type: 'suffix', category: 'locative', englishSuffix: ' on ' },
  { morpheme: 'squia', type: 'suffix', category: 'conditional', englishSuffix: ' would ' },
  { morpheme: 'tech', type: 'suffix', category: 'locative', englishPrefix: 'next to ' },
  { morpheme: 'tia', type: 'suffix', category: 'causative', englishSuffix: ' cause to ' },
  { morpheme: 'tic', type: 'suffix', category: 'adjectivizer', englishSuffix: '-like' },
  { morpheme: 'tin', type: 'suffix', category: 'plural' },
  { morpheme: 'tl', type: 'suffix', category: 'absolutive', nominalizing: true, countable: true },
  { morpheme: 'tli', type: 'suffix', category: 'absolutive', nominalizing: true, countable: true },
  { morpheme: 'ton', type: 'suffix', category: 'diminutive', englishPrefix: 'small ' },
  { morpheme: 'tza', type: 'suffix', category: 'imperfect', englishSuffix: 'ing' },
  { morpheme: 'tzin', type: 'suffix', category: 'sacred_diminutive', englishPrefix: 'small ' },
  { morpheme: 'tzitzin', type: 'suffix', category: 'sacred_diminutive', isPlural: true, englishPrefix: 'small ' },
  { morpheme: 'uh', type: 'suffix', category: 'possessive' },
  { morpheme: 'xoh', type: 'suffix', category: 'qualifier', englishPrefix: 'full of ' },
  { morpheme: 'ya', type: 'suffix', category: 'imperfect', englishSuffix: 'ing' },
  { morpheme: 'yan', type: 'suffix', category: 'locative_of_action', englishSuffix: ' place where one ' },
  { morpheme: 'yoh', type: 'suffix', category: 'qualifier', englishPrefix: 'full of ' },
  { morpheme: 'z', type: 'suffix', category: 'future', englishSuffix: ' will ' },
  { morpheme: 'zoh', type: 'suffix', category: 'qualifier', englishPrefix: 'full of ' },
];
