export const verbStems = [
  { morpheme: 'ahci', type: 'verb_stem', english: 'arrive' },
  { morpheme: 'ahhua', type: 'verb_stem', english: 'scold' },
  { morpheme: 'ahqui', type: 'verb_stem', english: 'swim', past: 'swam', pp: 'swum', agent: 'swimmer' },
  { morpheme: 'ana', type: 'verb_stem', english: 'sieze' },
  { morpheme: 'cahua', type: 'verb_stem', english: 'leave', past: 'left', pp: 'left' },
  { morpheme: 'caqui', type: 'verb_stem', english: 'hear', past: 'heard', pp: 'heard' },
  { morpheme: 'centlalia', type: 'verb_stem', english: 'gather' },
  { morpheme: 'chihua', type: 'verb_stem', english: 'make', past: 'made', pp: 'made' },
  { morpheme: 'choca', type: 'verb_stem', english: 'cry', past: 'cried', pp: 'cried', thirdSing: 'cries' },
  { morpheme: 'choloa', type: 'verb_stem', english: 'escape' },
  { morpheme: 'cochi', type: 'verb_stem', english: 'sleep', past: 'slept', pp: 'slept' },
  { morpheme: 'cocoa', type: 'verb_stem', english: 'hurt', past: 'hurt', pp: 'hurt' },
  { morpheme: 'cocolia', type: 'verb_stem', english: 'hate' },
  { morpheme: 'cohua', type: 'verb_stem', english: 'buy', past: 'bought', pp: 'bought' },
  { morpheme: 'cua', type: 'verb_stem', english: 'eat', past: 'ate', pp: 'eaten' },
  { morpheme: 'cueponi', type: 'verb_stem', english: 'bloom' },
  { morpheme: 'cui', type: 'verb_stem', english: 'take', past: 'took', pp: 'taken' },
  { morpheme: 'ehua', type: 'verb_stem', english: 'get up', past: 'got up', pp: 'gotten up' },
  { morpheme: 'hcuiloa', type: 'verb_stem', english: 'write', past: 'wrote', pp: 'written', fullStem: 'ihcuiloa' },
  { morpheme: 'htoa', type: 'verb_stem', english: 'say', past: 'said', pp: 'said', fullStem: 'ihtoa' },
  { morpheme: 'huetzca', type: 'verb_stem', english: 'laugh' },
  { morpheme: 'huica', type: 'verb_stem', english: 'sing', past: 'sang', pp: 'sung' },
  //{ morpheme: 'i', type: 'verb_stem', english: 'drink', past: 'drank', pp: 'drunk' },
  { morpheme: 'ihcuiloa', type: 'verb_stem', english: 'write', past: 'wrote', pp: 'written' },
  { morpheme: 'ihtoa', type: 'verb_stem', english: 'say', past: 'said', pp: 'said' },
  { morpheme: 'itta', type: 'verb_stem', english: 'see', past: 'saw', pp: 'seen' },
  { morpheme: 'iza', type: 'verb_stem', english: 'wake up', past: 'woke up', pp: 'woken up' },
  { morpheme: 'lemeni', type: 'verb_stem', english: 'burn' },
  { morpheme: 'maca', type: 'verb_stem', english: 'give', past: 'gave', pp: 'given' },
  { morpheme: 'maltia', type: 'verb_stem', english: 'bathe' },
  { morpheme: 'mati', type: 'verb_stem', english: 'know', past: 'knew', pp: 'known' },
  { morpheme: 'mihtotia', type: 'verb_stem', english: 'dance' },
  { morpheme: 'miqui', type: 'verb_stem', english: 'die' },
  { morpheme: 'motlaloa', type: 'verb_stem', english: 'run', past: 'ran', pp: 'run' },
  { morpheme: 'namaca', type: 'verb_stem', english: 'sell', past: 'sold', pp: 'sold' },
  { morpheme: 'nemi', type: 'verb_stem', english: 'live' },
  { morpheme: 'nequi', type: 'verb_stem', english: 'want' },
  { morpheme: 'neci', type: 'verb_stem', english: 'seem' },
  { morpheme: 'notza', type: 'verb_stem', english: 'call' },
  { morpheme: 'pano', type: 'verb_stem', english: 'pass' },
  { morpheme: 'pata', type: 'verb_stem', english: 'change' },
  { morpheme: 'patlani', type: 'verb_stem', english: 'fly', past: 'flew', pp: 'flown' },
  { morpheme: 'pitza', type: 'verb_stem', english: 'blow', past: 'blew', pp: 'blown' },
  { morpheme: 'polihui', type: 'verb_stem', english: 'perish' },
  { morpheme: 'pohua', type: 'verb_stem', english: 'read', past: 'read', pp: 'read' },
  { morpheme: 'quixtia', type: 'verb_stem', english: 'remove' },
  { morpheme: 'quiza', type: 'verb_stem', english: 'go out', past: 'went out', pp: 'gone out', thirdSing: 'goes out' },
  { morpheme: 'temoa', type: 'verb_stem', english: 'look for', past: 'looked for', pp: 'looked for' },
  { morpheme: 'temoc', type: 'verb_stem', english: 'descend' },
  { morpheme: 'tequihuia', type: 'verb_stem', english: 'volunteer' },
  { morpheme: 'tetiya', type: 'verb_stem', english: 'harden' },
  { morpheme: 'tlalia', type: 'verb_stem', english: 'put', past: 'put', pp: 'put' },
  { morpheme: 'tlahpaloz', type: 'verb_stem', english: 'greet' },
  //{ morpheme: 'tlahtoa', type: 'verb_stem', english: 'speak', past: 'spoke', pp: 'spoken' }, // should parse as "tla" + "htoa"
  { morpheme: 'tlatia', type: 'verb_stem', english: 'burn' },
  { morpheme: 'tlaquetza', type: 'verb_stem', english: 'build', past: 'built', pp: 'built' },
  { morpheme: 'tlayi', type: 'verb_stem', english: 'till' },
  { morpheme: 'tlazoh', type: 'verb_stem', english: 'love' },
  { morpheme: 'tlazohtla', type: 'verb_stem', english: 'love' },
  { morpheme: 'toca', type: 'verb_stem', english: 'plant' },
  { morpheme: 'tohua', type: 'verb_stem', english: 'sow', past: 'sowed', pp: 'sown' },
  { morpheme: 'tta', type: 'verb_stem', english: 'see', past: 'saw', pp: 'seen', fullStem: 'itta' },
  { morpheme: 'tzacua', type: 'verb_stem', english: 'close' },
  { morpheme: 'tzacui', type: 'verb_stem', english: 'close' },
  { morpheme: 'tzahtzi', type: 'verb_stem', english: 'shout' },
  { morpheme: 'tzicui', type: 'verb_stem', english: 'take', past: 'took', pp: 'taken' },
  { morpheme: 'xochiya', type: 'verb_stem', english: 'bloom' },
  { morpheme: 'yauh', type: 'verb_stem', english: 'go', past: 'went', pp: 'gone', thirdSing: 'goes' },
  { morpheme: 'yoli', type: 'verb_stem', english: 'live' },
  { morpheme: 'za', type: 'verb_stem', english: 'say', past: 'said', pp: 'said' },
];
