export const nahuatlLexicon = [
  // Particles
  { morpheme: 'achtopa', type: 'particle', english: 'first' },
  { morpheme: 'ahmo', type: 'particle', english: 'no, not' },
  { morpheme: 'amo', type: 'particle', english: 'no, not' },
  { morpheme: 'auh', type: 'particle', english: 'and then' },
  { morpheme: 'axcanah', type: 'particle', english: 'no' },
  { morpheme: 'ca', type: 'particle', english: 'truly, indeed' },
  { morpheme: 'ce', type: 'particle', english: 'a, one' },
  { morpheme: 'cenca', type: 'particle', english: 'very' },
  { morpheme: 'huan', type: 'particle', english: 'and' },
  { morpheme: 'inin', type: 'particle', english: 'this' },
  { morpheme: 'inon', type: 'particle', english: 'that' },
  { morpheme: 'itztoc', type: 'particle', english: "it's here" },
  { morpheme: 'no', type: 'particle', english: 'also' },
  { morpheme: 'oc', type: 'particle', english: 'still, yet' },
  { morpheme: 'peh', type: 'particle', english: 'then, so' },
  { morpheme: 'quemah', type: 'particle', english: 'yes' },
  { morpheme: 'quemeh', type: 'particle', english: 'like' },
  { morpheme: 'quena', type: 'particle', english: 'yes' },
  { morpheme: 'san', type: 'particle', english: 'only, just' },
  { morpheme: 'tel', type: 'particle', english: 'but' },
  { morpheme: 'yuhquin', type: 'particle', english: 'like this' },
  { morpheme: 'zan', type: 'particle', english: 'only, just' },

  // Interrogatives
  { morpheme: 'ac', type: 'interrogative', english: 'who (singular)' },
  { morpheme: 'acquiya', type: 'interrogative', english: 'who' },
  { morpheme: 'aquin', type: 'interrogative', english: 'who (plural)' },
  { morpheme: 'canin', type: 'interrogative', english: 'where' },
  { morpheme: 'cuix', type: 'interrogative', english: 'interrogative particle (yes/no)' },
  { morpheme: 'quemman', type: 'interrogative', english: 'when' },
  { morpheme: 'quenamih', type: 'interrogative', english: 'how' },
  { morpheme: 'quenqeh', type: 'interrogative', english: 'why' },
  { morpheme: 'queniuhqui', type: 'interrogative', english: 'how' },
  { morpheme: 'tleh', type: 'interrogative', english: 'what' },
  { morpheme: 'tlein', type: 'interrogative', english: 'what' },
  { morpheme: 'tlen', type: 'interrogative', english: 'what' },

  // Adverbs
  { morpheme: 'namantzin', type: 'adverb', english: 'now' },
  { morpheme: 'nican', type: 'adverb', english: 'here' },

  // Adjectives
  { morpheme: 'cuecuetztzin', type: 'adjective', english: 'small' },
  { morpheme: 'hueyi', type: 'adjective', english: 'big' },
  { morpheme: 'xoxoctic', type: 'adjective', english: 'blue, green' },
  { morpheme: 'yayahuic', type: 'adjective', english: 'black' },

  // Interjections
  { morpheme: 'tlazcamati', type: 'interjection', english: 'thank you' },
  { morpheme: 'tlazohcamati', type: 'interjection', english: 'thank you' },

  // Numerals
  { morpheme: 'ome', type: 'numeral', english: 'two'},
  { morpheme: 'eyi', type: 'numeral', english: 'three'},
  { morpheme: 'nahui', type: 'numeral', english: 'four'},
  { morpheme: 'macuilli', type: 'numeral', english: 'five'},
  { morpheme: 'chicuace', type: 'numeral', english: 'six'},
  { morpheme: 'chicome', type: 'numeral', english: 'seven'},
  { morpheme: 'chicueyi', type: 'numeral', english: 'eight'},
  { morpheme: 'chicnahui', type: 'numeral', english: 'nine'},
  { morpheme: 'mahtlactli', type: 'numeral', english: 'ten'},

  // Subject prefixes
  { morpheme: 'am', type: 'prefix', role: 'subject', person: 'second', number: 'plural', english: 'you (pl)' },
  { morpheme: 'an', type: 'prefix', role: 'subject', person: 'second', number: 'plural', english: 'you (pl)' },
  { morpheme: 'n', type: 'prefix', role: 'subject', person: 'first', number: 'singular', english: 'I' },
  { morpheme: 'ni', type: 'prefix', role: 'subject', person: 'first', number: 'singular', english: 'I' },
  { morpheme: 't', type: 'prefix', role: 'subject', person: 'first', number: 'plural', english: 'we'},
  { morpheme: 't', type: 'prefix', role: 'subject', person: 'second', number: 'singular', english: 'you (sg)'},
  { morpheme: 'ti', type: 'prefix', role: 'subject', person: 'first', number: 'plural', english: 'we'},
  { morpheme: 'ti', type: 'prefix', role: 'subject', person: 'second', number: 'singular', english: 'you (sg)'},

  // Object prefixes
  { morpheme: 'amech', type: 'prefix', role: 'object', person: 'second', number: 'plural', english: 'you (pl)' },
  { morpheme: 'c', type: 'prefix', role: 'object', person: 'third', number: 'singular', english: 'him/her/it' },
  { morpheme: 'mitz', type: 'prefix', role: 'object', person: 'second', number: 'singular', english: 'you (sg)' },
  { morpheme: 'nech', type: 'prefix', role: 'object', person: 'first', number: 'singular', english: 'me' },
  { morpheme: 'qu', type: 'prefix', role: 'object', person: 'third', number: 'singular', english: 'him/her/it' },
  { morpheme: 'qui', type: 'prefix', role: 'object', person: 'third', number: 'singular', english: 'him/her/it' },
  { morpheme: 'quim', type: 'prefix', role: 'object', person: 'third', number: 'plural', english: 'them' },
  { morpheme: 'quin', type: 'prefix', role: 'object', person: 'third', number: 'plural', english: 'them' },
  { morpheme: 'te', type: 'prefix', role: 'object', impliesSomeone: true },
  { morpheme: 'tech', type: 'prefix', role: 'object', person: 'first', number: 'plural', english: 'us' },
  { morpheme: 'tla', type: 'prefix', role: 'object', impliesSomething: true },

  // Imperative prefixes
  { morpheme: 'x', type: 'prefix', category: 'imperative', english: 'you (sg/pl)', replacesSubject: true }, // For xi- before vowels
  { morpheme: 'xi', type: 'prefix', category: 'imperative', english: 'you (sg/pl)', replacesSubject: true }, // New entry for imperative prefix

  // Possessive/reflexive prefixes
  { morpheme: 'am', type: 'prefix', role: 'possessive', person: 'second', number: 'plural', english: 'your (pl)', usedWith: 'noun' },
  { morpheme: 'amo', type: 'prefix', role: 'possessive', person: 'second', number: 'plural', english: 'your (pl)', usedWith: 'noun' },
  { morpheme: 'i', type: 'prefix', role: 'possessive', person: 'third', number: 'singular', english: 'his/her/its', usedWith: 'noun' },
  { morpheme: 'im', type: 'prefix', role: 'possessive', person: 'third', number: 'plural', english: 'their', usedWith: 'noun' },
  { morpheme: 'in', type: 'prefix', role: 'possessive', person: 'third', number: 'plural', english: 'their', usedWith: 'noun' },
  { morpheme: 'm', type: 'prefix', role: 'possessive', person: 'second', number: 'singular', english: 'your (sg)', usedWith: 'noun' },
  { morpheme: 'm', type: 'prefix', role: 'reflexive', person: 'second', number: 'singular', english: 'yourself (sg)', usedWith: 'verb' },
  { morpheme: 'mo', type: 'prefix', role: 'possessive', person: 'second', number: 'singular', english: 'your (sg)', usedWith: 'noun' },
  { morpheme: 'mo', type: 'prefix', role: 'reflexive', person: 'second', number: 'singular', english: 'yourself (sg)', usedWith: 'verb' },
  { morpheme: 'mo', type: 'prefix', role: 'reflexive', person: 'second', number: 'plural', english: 'yourselves', usedWith: 'verb' },
  { morpheme: 'mo', type: 'prefix', role: 'reflexive', person: 'third', number: 'singular', english: 'him/her/itself', usedWith: 'verb' },
  { morpheme: 'n', type: 'prefix', role: 'possessive', person: 'first', number: 'singular', english: 'my', usedWith: 'noun' },
  { morpheme: 'n', type: 'prefix', role: 'reflexive', person: 'first', number: 'singular', english: 'myself', usedWith: 'verb' },
  { morpheme: 'no', type: 'prefix', role: 'possessive', person: 'first', number: 'singular', english: 'my', usedWith: 'noun' },
  { morpheme: 'no', type: 'prefix', role: 'reflexive', person: 'first', number: 'singular', english: 'myself', usedWith: 'verb' },
  { morpheme: 't', type: 'prefix', role: 'possessive', person: 'first', number: 'plural', english: 'our', usedWith: 'noun' },
  { morpheme: 't', type: 'prefix', role: 'reflexive', person: 'first', number: 'plural', english: 'ourselves', usedWith: 'verb' },
  { morpheme: 'to', type: 'prefix', role: 'possessive', person: 'first', number: 'plural', english: 'our', usedWith: 'noun' },
  { morpheme: 'to', type: 'prefix', role: 'reflexive', person: 'first', number: 'plural', english: 'ourselves', usedWith: 'verb' },

  // Other existing prefixes
  { morpheme: 'ah', type: 'prefix', role: 'negation', english: 'not' },

  // Verb Stems (only irregular thirdSing forms kept)
  { morpheme: 'ahci', type: 'verb_stem', english: 'arrive'},
  { morpheme: 'ahhua', type: 'verb_stem', english: 'scold'},
  { morpheme: 'ahqui', type: 'verb_stem', english: 'swim', past: 'swam', pp: 'swum', agent: 'swimmer'},
  { morpheme: 'cahua', type: 'verb_stem', english: 'leave', past: 'left', pp: 'left' },
  { morpheme: 'caqui', type: 'verb_stem', english: 'hear', past: 'heard', pp: 'heard' },
  { morpheme: 'centlalia', type: 'verb_stem', english: 'gather'},
  { morpheme: 'chihua', type: 'verb_stem', english: 'make', past: 'made', pp: 'made' },
  { morpheme: 'choca', type: 'verb_stem', english: 'cry', past: 'cried', pp: 'cried', thirdSing: 'cries' },
  { morpheme: 'choloa', type: 'verb_stem', english: 'escape'},
  { morpheme: 'cochi', type: 'verb_stem', english: 'sleep', past: 'slept', pp: 'slept' },
  { morpheme: 'cocoa', type: 'verb_stem', english: 'hurt', past: 'hurt', pp: 'hurt' },
  { morpheme: 'cocolia', type: 'verb_stem', english: 'hate' },
  { morpheme: 'cohua', type: 'verb_stem', english: 'buy', past: 'bought', pp: 'bought' },
  { morpheme: 'cua', type: 'verb_stem', english: 'eat', past: 'ate', pp: 'eaten' },
  { morpheme: 'cueponi', type: 'verb_stem', english: 'bloom'},
  { morpheme: 'cui', type: 'verb_stem', english: 'take', past: 'took', pp: 'taken' },
  { morpheme: 'ehua', type: 'verb_stem', english: 'get up', past: 'got up', pp: 'gotten up' },
  { morpheme: 'huetzca', type: 'verb_stem', english: 'laugh' },
  { morpheme: 'huica', type: 'verb_stem', english: 'sing', past: 'sang', pp: 'sung' },
  { morpheme: 'ihtoa', type: 'verb_stem', english: 'say', past: 'said', pp: 'said' },
  { morpheme: 'itta', type: 'verb_stem', english: 'see', past: 'saw', pp: 'seen' },
  { morpheme: 'iza', type: 'verb_stem', english: 'wake up', past: 'woke up', pp: 'woken up' },
  { morpheme: 'lemeni', type: 'verb_stem', english: 'burn' },
  { morpheme: 'maca', type: 'verb_stem', english: 'give', past: 'gave', pp: 'given' },
  { morpheme: 'maltia', type: 'verb_stem', english: 'bathe'},
  { morpheme: 'mati', type: 'verb_stem', english: 'know', past: 'knew', pp: 'known' },
  { morpheme: 'mihtotia', type: 'verb_stem', english: 'dance'},
  { morpheme: 'motlaloa', type: 'verb_stem', english: 'run', past: 'ran', pp: 'run' },
  { morpheme: 'namaca', type: 'verb_stem', english: 'sell', past: 'sold', pp: 'sold' },
  { morpheme: 'nemi', type: 'verb_stem', english: 'live'},
  { morpheme: 'nequi', type: 'verb_stem', english: 'want'},
  { morpheme: 'nesi', type: 'verb_stem', english: 'seem'},
  { morpheme: 'pano', type: 'verb_stem', english: 'pass'},
  { morpheme: 'pata', type: 'verb_stem', english: 'change'},
  { morpheme: 'patlani', type: 'verb_stem', english: 'fly', past: 'flew', pp: 'flown' },
  { morpheme: 'pitza', type: 'verb_stem', english: 'blow', past: 'blew', pp: 'blown' },
  { morpheme: 'polihui', type: 'verb_stem', english: 'perish'},
  { morpheme: 'pohua', type: 'verb_stem', english: 'read', past: 'read', pp: 'read' },
  { morpheme: 'quixtia', type: 'verb_stem', english: 'remove'},
  { morpheme: 'quiza', type: 'verb_stem', english: 'go out', past: 'went out', pp: 'gone out', thirdSing: 'goes out' },
  { morpheme: 'temoa', type: 'verb_stem', english: 'look for', past: 'looked for', pp: 'looked for' },
  { morpheme: 'temoc', type: 'verb_stem', english: 'descend'},
  { morpheme: 'tetiya', type: 'verb_stem', english: 'harden' },
  { morpheme: 'tlalia', type: 'verb_stem', english: 'put', past: 'put', pp: 'put' },
  { morpheme: 'tlatia', type: 'verb_stem', english: 'burn' },
  { morpheme: 'tlayi', type: 'verb_stem', english: 'till' },
  { morpheme: 'tlaquetza', type: 'verb_stem', english: 'build', past: 'built', pp: 'built' },
  { morpheme: 'tlazoh', type: 'verb_stem', english: 'love'},
  { morpheme: 'toca', type: 'verb_stem', english: 'plant'},
  { morpheme: 'tohua', type: 'verb_stem', english: 'sow', past: 'sowed', pp: 'sown' },
  { morpheme: 'tzacua', type: 'verb_stem', english: 'close' },
  { morpheme: 'tzahtzi', type: 'verb_stem', english: 'shout'},
  { morpheme: 'tzicui', type: 'verb_stem', english: 'take', past: 'took', pp: 'taken' },
  { morpheme: 'xochiya', type: 'verb_stem', english: 'bloom'},
  { morpheme: 'yauh', type: 'verb_stem', english: 'go', past: 'went', pp: 'gone', thirdSing: 'goes' },
  { morpheme: 'za', type: 'verb_stem', english: 'say', past: 'said', pp: 'said' },

  // Noun Stems
  //{ morpheme: "a", type: "noun_stem", english: "water", countable: false, animate: false },
  { morpheme: 'acal', type: 'noun_stem', english: 'boat', countable: true, animate: false },
  { morpheme: 'ahui', type: 'noun_stem', english: 'aunt', countable: true, animate: true },
  { morpheme: 'altepe', type: 'noun_stem', english: 'city', countable: true, animate: false },
  { morpheme: 'ama', type: 'noun_stem', english: 'paper', countable: false, animate: false },
  { morpheme: 'amanal', type: 'noun_stem', english: 'pond', countable: true, animate: false },
  { morpheme: 'amol', type: 'noun_stem', english: 'soap', countable: true, animate: false },
  { morpheme: 'amox', type: 'noun_stem', english: 'book', countable: true, animate: false },
  { morpheme: 'ayo', type: 'noun_stem', english: 'turtle', countable: true, animate: true },
  { morpheme: 'cac', type: 'noun_stem', english: 'sandal', countable: true, animate: false},
  { morpheme: 'cacahua', type: 'noun_stem', english: 'cacao', countable: false, animate: false },
  { morpheme: 'cacaoh', type: 'noun_stem', english: 'cacao', countable: false, animate: false, absolutiveSuffix: false },
  { morpheme: 'cahuayoh', type: 'noun_stem', english: 'horse', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'cal', type: 'noun_stem', english: 'house', countable: true, animate: false },
  { morpheme: 'camoh', type: 'noun_stem', english: 'yam', countable: true, animate: false },
  { morpheme: 'cen', type: 'noun_stem', english: 'one', countable: false, animate: false },
  { morpheme: 'chahuiz', type: 'noun_stem', english: 'fungus', countable: false, animate: false },
  { morpheme: 'chan', type: 'noun_stem', english: 'house', countable: true, animate: false },
  { morpheme: 'chichi', type: 'noun_stem', english: 'dog', countable: true, animate: true },
  { morpheme: 'chil', type: 'noun_stem', english: 'chili', countable: true, animate: false },
  { morpheme: 'cihua', type: 'noun_stem', english: 'woman', englishPlural: 'women', countable: true, animate: true },
  { morpheme: 'citlalin', type: 'noun_stem', english: 'star', countable: true, animate: false, absolutiveSuffix: false },
  { morpheme: 'coa', type: 'noun_stem', english: 'serpent', countable: true, animate: true },
  { morpheme: 'comi', type: 'noun_stem', english: 'pot', countable: true, animate: false },
  { morpheme: 'coyo', type: 'noun_stem', english: 'coyote', countable: true, animate: true },
  { morpheme: 'cuahui', type: 'noun_stem', english: 'tree', countable: true, animate: false },
  { morpheme: 'cuapuertah', type: 'noun_stem', english: 'door', countable: true, animate: false, absolutiveSuffix: false },
  { morpheme: 'cuatochin', type: 'noun_stem', english: 'rabbit', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'cuauh', type: 'noun_stem', english: 'eagle', countable: true, animate: true },
  { morpheme: 'cueya', type: 'noun_stem', english: 'frog', englishPlural: 'frogs', countable: true, animate: true },
  { morpheme: 'e', type: 'noun_stem', english: 'bean', countable: true, animate: false },
  { morpheme: 'eheca', type: 'noun_stem', english: 'wind', countable: false, animate: false },
  { morpheme: 'huacax', type: 'noun_stem', english: 'cow', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'ichca', type: 'noun_stem', english: 'sheep', englishPlural: 'sheep', countable: true, animate: true },
  { morpheme: 'ichpoca', type: 'noun_stem', english: 'teen girl', countable: true, animate: true },
  { morpheme: 'ichpoch', type: 'noun_stem', english: 'girl', countable: true, animate: true },
  { morpheme: 'icniuh', type: 'noun_stem', english: 'friend', countable: true, animate: true },
  { morpheme: 'macehual', type: 'noun_stem', english: 'person', englishPlural: 'people', countable: true, animate: true },
  { morpheme: 'maxochi', type: 'noun_stem', english: 'gay man', englishPlural: 'gay men', countable: true, animate: true },
  { morpheme: 'me', type: 'noun_stem', english: 'mageuy', countable: true, animate: false },
  { morpheme: 'meca', type: 'noun_stem', english: 'rope', countable: true, animate: false },
  { morpheme: 'michi', type: 'noun_stem', english: 'fish', countable: true, animate: true },
  { morpheme: 'michin', type: 'noun_stem', english: 'fish', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'mizton', type: 'noun_stem', english: 'cat', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'mol', type: 'noun_stem', english: 'sauce', countable: true, animate: false },
  { morpheme: 'mocauhqui', type: 'noun_stem', english: 'married person', englishPlural: 'married people', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'namacac', type: 'noun_stem', english: 'seller', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'nan', type: 'noun_stem', english: 'mother', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'nanan', type: 'noun_stem', english: 'mother', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'necuh', type: 'noun_stem', english: 'honey', countable: false, animate: false },
  { morpheme: 'nemilis', type: 'noun_stem', english: 'life', countable: true, animate: true },
  { morpheme: 'ocuili', type: 'noun_stem', english: 'worm', countable: true, animate: true },
  { morpheme: 'ocuilin', type: 'noun_stem', english: 'worm', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'oh', type: 'noun_stem', english: 'path', countable: true, animate: false },
  { morpheme: 'on', type: 'noun_stem', english: 'two', countable: false, animate: false },
  { morpheme: 'oquich', type: 'noun_stem', english: 'man', englishPlural: 'men', countable: true, animate: true },
  { morpheme: 'oquichpil', type: 'noun_stem', english: 'boy', countable: true, animate: true },
  { morpheme: 'pah', type: 'noun_stem', english: 'medicine', countable: false, animate: false },
  { morpheme: 'pahuax', type: 'noun_stem', english: 'cooked', countable: true, animate: false },
  { morpheme: 'pami', type: 'noun_stem', english: 'banner', countable: true, animate: false },
  { morpheme: 'pantalon', type: 'noun_stem', english: 'pants', countable: false, animate: false, absolutiveSuffix: false },
  { morpheme: 'papalo', type: 'noun_stem', english: 'butterfly', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'patox', type: 'noun_stem', english: 'duck', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'pil', type: 'noun_stem', english: 'noble', countable: true, animate: true },
  { morpheme: 'pitzo', type: 'noun_stem', english: 'pig', countable: true, animate: true },
  { morpheme: 'piyo', type: 'noun_stem', english: 'chicken', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'quetzal', type: 'noun_stem', english: 'quetzal feather', countable: true, animate: false },
  { morpheme: 'tamal', type: 'noun_stem', english: 'tamal', englishPlural: 'tamales', countable: true, animate: false },
  { morpheme: 'te', type: 'noun_stem', english: 'stone', countable: true, animate: false },
  { morpheme: 'tecciz', type: 'noun_stem', english: 'egg', countable: true, animate: false },
  { morpheme: 'tecuh', type: 'noun_stem', english: 'lord', countable: true, animate: true },
  { morpheme: 'tecoh', type: 'noun_stem', english: 'lord', countable: true, animate: true },
  { morpheme: 'telpoca', type: 'noun_stem', english: 'teen boy', countable: true, animate: true },
  { morpheme: 'tepe', type: 'noun_stem', english: 'hill', countable: true, animate: false },
  { morpheme: 'tepos', type: 'noun_stem', english: 'metal', countable: false, animate: false },
  { morpheme: 'tequi', type: 'noun_stem', english: 'work', countable: false, animate: false },
  { morpheme: 'tiyanquiz', type: 'noun_stem', english: 'market', countable: true, animate: false },
  { morpheme: 'tlaca', type: 'noun_stem', english: 'man', englishPlural: 'men', countable: true, animate: true },
  { morpheme: 'tlahtol', type: 'noun_stem', english: 'word', countable: true, animate: false },
  { morpheme: 'tlal', type: 'noun_stem', english: 'land', countable: false, animate: false },
  { morpheme: 'tlaltipac', type: 'noun_stem', english: 'world', countable: true, animate: false },
  { morpheme: 'tlatsotson', type: 'noun_stem', english: 'music', countable: false, animate: false },
  { morpheme: 'toca', type: 'noun_stem', english: 'spider', countable: true, animate: true },
  { morpheme: 'toch', type: 'noun_stem', english: 'rabbit', countable: true, animate: true },
  { morpheme: 'toma', type: 'noun_stem', english: 'tomato', englishPlural: 'tomatoes', countable: true, animate: false },
  { morpheme: 'tomin', type: 'noun_stem', english: 'coin', countable: true, animate: false, absolutiveSuffix: false },
  { morpheme: 'tonatiuh', type: 'noun_stem', english: 'sun', countable: true, animate: false, absolutiveSuffix: false },
  { morpheme: 'toroh', type: 'noun_stem', english: 'bull', countable: true, animate: true, absolutiveSuffix: false },
  { morpheme: 'toto', type: 'noun_stem', english: 'bird', countable: true, animate: true },
  { morpheme: 'tzapo', type: 'noun_stem', english: 'sapote', countable: true, animate: false },
  { morpheme: 'xochi', type: 'noun_stem', english: 'flower', countable: true, animate: false },
  { morpheme: 'yollo', type: 'noun_stem', english: 'heart', countable: true, animate: true },
  { morpheme: 'zayolin', type: 'noun_stem', english: 'fly', countable: true, animate: true, absolutiveSuffix: false },

  // Suffixes
  { morpheme: 'ah', type: 'suffix', category: 'unspecified', englishPrefix: 'some' },
  { morpheme: 'ca', type: 'suffix', category: 'locative', englishSuffix: ' place' },
  { morpheme: 'can', type: 'suffix', category: 'locative', englishPrefix: 'place of' },
  { morpheme: 'can', type: 'suffix', category: 'plural' },
  { morpheme: 'co', type: 'suffix', category: 'locative', englishPrefix: 'place on ' },
  { morpheme: 'eh', type: 'suffix', category: 'possessive', englishSuffix: ' owner' },
  { morpheme: 'h', type: 'suffix', category: 'plural' },
  { morpheme: 'hua', type: 'suffix', category: 'possessive', englishSuffix: ' owner of ' },
  { morpheme: 'huan', type: 'suffix', category: 'plural' },
  { morpheme: 'huia', type: 'suffix', category: 'applicative', englishSuffix: ' for ' },
  { morpheme: 'ic', type: 'suffix', category: 'instrumental', englishSuffix: ' with ' },
  { morpheme: 'li', type: 'suffix', category: 'absolutive', nominalizing: true, countable: true },
  { morpheme: 'lia', type: 'suffix', category: 'applicative', englishSuffix: ' for ' },
  { morpheme: 'liztli', type: 'suffix', category: 'nominalizer', englishSuffix: 'ing', nominalizing: true, countable: true },
  { morpheme: 'lli', type: 'suffix', category: 'participle', nominalizing: true, countable: true },
  { morpheme: 'me', type: 'suffix', category: 'plural' },
  { morpheme: 'meh', type: 'suffix', category: 'plural' },
  { morpheme: 'ni', type: 'suffix', category: 'habitual', englishSuffix: 'er', nominalizing: true, countable: true },
  { morpheme: 'oa', type: 'suffix', category: 'transitivizer', englishSuffix: ' to (do something)' },
  { morpheme: 'pan', type: 'suffix', category: 'locative', englishSuffix: ' on ' },
  { morpheme: 'squia', type: 'suffix', category: 'conditional', englishSuffix: ' would ' },
  { morpheme: 'tech', type: 'suffix', category: 'locative', englishPrefix: 'next to ' },
  { morpheme: 'tia', type: 'suffix', category: 'causative', englishSuffix: ' cause to ' },
  { morpheme: 'tic', type: 'suffix', category: 'adjectivizer', englishSuffix: '-like' },
  { morpheme: 'tin', type: 'suffix', category: 'plural' },
  { morpheme: 'tl', type: 'suffix', category: 'absolutive', nominalizing: true, countable: true },
  { morpheme: 'tli', type: 'suffix', category: 'absolutive', nominalizing: true, countable: true },
  { morpheme: 'ton', type: 'suffix', category: 'diminutive', englishPrefix: 'small ' },
  { morpheme: 'tza', type: 'suffix', category: 'imperfect', englishSuffix: 'ing' },
  { morpheme: 'tzin', type: 'suffix', category: 'honorific', englishPrefix: 'respected ' },
  { morpheme: 'uh', type: 'suffix', category: 'possessive' },
  { morpheme: 'xoh', type: 'suffix', category: 'qualifier', englishPrefix: 'full of ' },
  { morpheme: 'ya', type: 'suffix', category: 'imperfect', englishSuffix: 'ing' },
  { morpheme: 'yan', type: 'suffix', category: 'locative_of_action', englishSuffix: ' place where one ' },
  { morpheme: 'yoh', type: 'suffix', category: 'qualifier', englishPrefix: 'full of ' },
  { morpheme: 'z', type: 'suffix', category: 'future', englishSuffix: ' will ' },
  { morpheme: 'zoh', type: 'suffix', category: 'qualifier', englishPrefix: 'full of ' },
];
