export const nahuatlLexicon = [
    // Particles
    { morpheme: "axcanah", type: "particle", english: "no" },
    { morpheme: "achtopa", type: "particle", english: "first" },
    { morpheme: "yuhquin", type: "particle", english: "like this" },
    { morpheme: "itztoc", type: "particle", english: "it's here" },
    { morpheme: "cenca", type: "particle", english: "very" },
    { morpheme: "quemah", type: "particle", english: "yes" },
    { morpheme: "quena", type: "particle", english: "yes" },
    { morpheme: "quemeh", type: "particle", english: "like" },
    { morpheme: "ahmo", type: "particle", english: "no, not" },
    { morpheme: "cuix", type: "interrogative", "english": "interrogative particle (yes/no)" },
    { morpheme: "san", type: "particle", english: "only, just" },
    { morpheme: "tel", type: "particle", english: "but" },
    { morpheme: "auh", type: "particle", english: "and then" },
    { morpheme: "amo", type: "particle", english: "no, not" },
    { morpheme: "ca", type: "particle", english: "truly, indeed" },
    { morpheme: "oc", type: "particle", english: "still, yet" },
    { morpheme: "huan", type: "particle", english: "and" },
    { morpheme: "no", type: "particle", english: "also" },
    { morpheme: "peh", type: "particle", english: "then, so" },
    { morpheme: "zan", type: "particle", english: "only, just" },

    // Interrogatives
    { morpheme: "aquin", type: "interrogative", english: "who (plural)" },
    { morpheme: "acquiya", type: "interrogative", english: "who" },
    { morpheme: "quemman", type: "interrogative", english: "when" },
    { morpheme: "quenqeh", type: "interrogative", english: "why" },
    { morpheme: "quenamih", type: "interrogative", english: "how" },
    { morpheme: "queniuhqui", type: "interrogative", english: "how" },
    { morpheme: "canin", type: "interrogative", english: "where" },
    { morpheme: "ac", type: "interrogative", english: "who (singular)" },
    { morpheme: "tleh", type: "interrogative", english: "what" },
    { morpheme: "tlen", type: "interrogative", english: "what" },
    { morpheme: "tlein", type: "interrogative", english: "what" },

    // Adverbs
    { morpheme: "nican", type: "adverb", english: "here" },

    // Prefixes
    { morpheme: "amech", type: "prefix", role: "object", person: "second", number: "plural", english: "you (pl)" },
    { morpheme: "mitz", type: "prefix", role: "object", person: "second", number: "singular", english: "you (sg)" },
    { morpheme: "tech", type: "prefix", role: "object", person: "first", number: "plural", english: "us" },
    { morpheme: "nech", type: "prefix", role: "object", person: "first", number: "singular", english: "me" },
    { morpheme: "quin", type: "prefix", role: "object", person: "third", number: "plural", english: "them" },
    { morpheme: "quim", type: "prefix", role: "object", person: "third", number: "plural", english: "them" },
    { morpheme: "qui", type: "prefix", role: "object", person: "third", number: "singular", english: "him/her/it" },
    { morpheme: "x", type: "prefix", category: "imperative", english: "you (sg/pl)", replaces_subject: true }, // For xi- before vowels
    { morpheme: "xi", type: "prefix", category: "imperative", english: "you (sg/pl)", replaces_subject: true }, // New entry for imperative prefix
    
    // Possessive/Reflexive
    { morpheme: "no", type: "prefix", role: "possessive", person: "first", number: "singular", english: "my", used_with: "noun" },
    { morpheme: "no", type: "prefix", role: "reflexive", person: "first", number: "singular", english: "myself", used_with: "verb" },
    { morpheme: "n", type: "prefix", role: "possessive", person: "first", number: "singular", english: "my", used_with: "noun" },
    { morpheme: "n", type: "prefix", role: "reflexive", person: "first", number: "singular", english: "myself", used_with: "verb" },
    { morpheme: "to", type: "prefix", role: "possessive", person: "first", number: "plural", english: "our", used_with: "noun" },
    { morpheme: "to", type: "prefix", role: "reflexive", person: "first", number: "plural", english: "ourselves", used_with: "verb" },
    { morpheme: "t", type: "prefix", role: "possessive", person: "first", number: "plural", english: "our", used_with: "noun" },
    { morpheme: "t", type: "prefix", role: "reflexive", person: "first", number: "plural", english: "ourselves", used_with: "verb" },

    { morpheme: "mo", type: "prefix", role: "possessive", person: "second", number: "singular", english: "your (sg)", used_with: "noun" },
    { morpheme: "mo", type: "prefix", role: "reflexive", person: "second", number: "singular", english: "yourself (sg)", used_with: "verb" },
    { morpheme: "mo", type: "prefix", role: "reflexive", person: "second", number: "plural", english: "yourselves", used_with: "verb" },
    { morpheme: "m", type: "prefix", role: "possessive", person: "second", number: "singular", english: "your (sg)", used_with: "noun" },
    { morpheme: "m", type: "prefix", role: "reflexive", person: "second", number: "singular", english: "yourself (sg)", used_with: "verb" },
    { morpheme: "amo", type: "prefix", role: "possessive", person: "second", number: "plural", english: "your (pl)", used_with: "noun" },
	{ morpheme: "am", type: "prefix", role: "possessive", person: "second", number: "plural", english: "your (pl)", used_with: "noun" },

    { morpheme: "i", type: "prefix", role: "possessive", person: "third", number: "singular", english: "his/her/its", used_with: "noun" },	
	{ morpheme: "in", type: "prefix", role: "possessive", person: "third", number: "plural", english: "their", used_with: "noun" },
	{ morpheme: "im", type: "prefix", role: "possessive", person: "third", number: "plural", english: "their", used_with: "noun" },
	{ morpheme: "mo", type: "prefix", role: "reflexive", person: "third", number: "singular", english: "him/her/itself", used_with: "verb" },

    // Other existing prefixes
    { morpheme: "tla", type: "prefix", role: "object", implies_something: true },
    { morpheme: "ah", type: "prefix", role: "negation", english: "not" },
    { morpheme: "am", type: "prefix", role: "subject", person: "second", number: "plural", english: "you (pl)" },
    { morpheme: "an", type: "prefix", role: "subject", person: "second", number: "plural", english: "you (pl)" },
    { morpheme: "ni", type: "prefix", role: "subject", person: "first", number: "singular", english: "I" },
    { morpheme: "qu", type: "prefix", role: "object", person: "third", number: "singular", english: "him/her/it" },
    { morpheme: "te", type: "prefix", role: "object", implies_someone: true },
    { morpheme: "ti", type: "prefix", role: "subject", person: "first", number: "plural", english: "we"},
    { morpheme: "ti", type: "prefix", role: "subject", person: "second", number: "singular", english: "you (sg)"},
    { morpheme: "t", type: "prefix", role: "subject", person: "first", number: "plural", english: "we"},
    { morpheme: "t", type: "prefix", role: "subject", person: "second", number: "singular", english: "you (sg)"},
    { morpheme: "c", type: "prefix", role: "object", person: "third", number: "singular", english: "him/her/it" },
    { morpheme: "n", type: "prefix", role: "subject", person: "first", number: "singular", english: "I" },

    // Verb Stems (only irregular third_sing forms kept)
    { morpheme: "mihtotia", type: "verb_stem", english: "dance"},
    { morpheme: "maltia", type: "verb_stem", english: "bathe"},
    { morpheme: "temoc", type: "verb_stem", english: "descend"},
    { morpheme: "choloa", type: "verb_stem", english: "escape"},
    { morpheme: "quiza", type: "verb_stem", english: "go out", past: "went out", pp: "gone out", third_sing: "goes out" },
    { morpheme: "huetzca", type: "verb_stem", english: "laugh" },
    { morpheme: "ahqui", type: "verb_stem", english: "swim", past: "swam", pp: "swum", agent: "swimmer"},
    { morpheme: "nequi", type: "verb_stem", english: "want"},
    { morpheme: "nemi", type: "verb_stem", english: "live"},
    { morpheme: "mati", type: "verb_stem", english: "know", past: "knew", pp: "known" },
    { morpheme: "choca", type: "verb_stem", english: "cry", past: "cried", pp: "cried", third_sing: "cries" },
    { morpheme: "cochi", type: "verb_stem", english: "sleep", past: "slept", pp: "slept" },
    { morpheme: "iza", type: "verb_stem", english: "wake up", past: "woke up", pp: "woken up" },
    { morpheme: "itta", type: "verb_stem", english: "see", past: "saw", pp: "seen" },
    { morpheme: "tlaquetza", type: "verb_stem", english: "build", past: "built", pp: "built" },
    { morpheme: "yauh", type: "verb_stem", english: "go", past: "went", pp: "gone", third_sing: "goes" },
    { morpheme: "za", type: "verb_stem", english: "say", past: "said", pp: "said" },
    { morpheme: "ehua", type: "verb_stem", english: "get up", past: "got up", pp: "gotten up" },
    { morpheme: "pano", type: "verb_stem", english: "pass"},
    { morpheme: "patlani", type: "verb_stem", english: "fly", past: "flew", pp: "flown" },
    { morpheme: "pata", type: "verb_stem", english: "change"},
    { morpheme: "ihtoa", type: "verb_stem", english: "say", past: "said", pp: "said" },
    { morpheme: "cueponi", type: "verb_stem", english: "bloom"},
    { morpheme: "cua", type: "verb_stem", english: "eat", past: "ate", pp: "eaten" },
    { morpheme: "chihua", type: "verb_stem", english: "make", past: "made", pp: "made" },
    { morpheme: "tlazoh", type: "verb_stem", english: "love"},
    { morpheme: "tzatzi", type: "verb_stem", english: "shout"},
    { morpheme: "ahci", type: "verb_stem", english: "arrive"},
    { morpheme: "temoa", type: "verb_stem", english: "look for", past: "looked for", pp: "looked for" },
    { morpheme: "tzicui", type: "verb_stem", english: "take", past: "took", pp: "taken" },
    { morpheme: "pohua", type: "verb_stem", english: "read", past: "read", pp: "read" },
    { morpheme: "quixtia", type: "verb_stem", english: "remove"},
    { morpheme: "itta", type: "verb_stem", english: "see", past: "saw", pp: "seen" },
    { morpheme: "namaca", type: "verb_stem", english: "sell", past: "sold", pp: "sold" },
    { morpheme: "cui", type: "verb_stem", english: "take", past: "took", pp: "taken" },
    { morpheme: "toca", type: "verb_stem", english: "plant"},
    { morpheme: "itta", type: "verb_stem", english: "see", past: "saw", pp: "seen" },
    { morpheme: "tohua", type: "verb_stem", english: "sow", past: "sowed", pp: "sown" },
    { morpheme: "xochiya", type: "verb_stem", english: "bloom"},
    { morpheme: "maca", type: "verb_stem", english: "give", past: "gave", pp: "given" },
    { morpheme: "huica", type: "verb_stem", english: "sing", past: "sang", pp: "sung" },
    { morpheme: "centlalia", type: "verb_stem", english: "gather"},
    { morpheme: "polihui", type: "verb_stem", english: "perish"},
    { morpheme: "tlalia", type: "verb_stem", english: "put", past: "put", pp: "put" },
    { morpheme: "pitza", type: "verb_stem", english: "blow", past: "blew", pp: "blown" },
    { morpheme: "cahua", type: "verb_stem", english: "leave", past: "left", pp: "left" },

    // Noun Stems
    { morpheme: "amol", type: "noun_stem", english: "soap", countable: true, animate: false },
    { morpheme: "acal", type: "noun_stem", english: "boat", countable: true, animate: false },
    { morpheme: "nacac", type: "noun_stem", english: "seller", countable: true, animate: false },
    { morpheme: "tequi", type: "noun_stem", english: "work", countable: false, animate: false },
    { morpheme: "pahuax", type: "noun_stem", english: "cooked", countable: true, animate: false },
    { morpheme: "namacac", type: "noun_stem", english: "seller", countable: true, animate: true, absolutive_suffix: false },
    { morpheme: "amanal", type: "noun_stem", english: "pond", countable: true, animate: false },
    { morpheme: "tlahtol", type: "noun_stem", english: "word", countable: true, animate: false },
    { morpheme: "cueya", type: "noun_stem", english: "frog", english_plural: "frogs", countable: true, animate: true },
    { morpheme: "cen", type: "noun_stem", english: "one", countable: false, animate: false },
    { morpheme: "on", type: "noun_stem", english: "two", countable: false, animate: false },
    { morpheme: "te", type: "noun_stem", english: "stone", countable: true, animate: false },
    { morpheme: "coyo", type: "noun_stem", english: "coyote", countable: true, animate: true },
    { morpheme: "cuauh", type: "noun_stem", english: "eagle", countable: true, animate: true },
    { morpheme: "cal", type: "noun_stem", english: "house", countable: true, animate: false },
    { morpheme: "mol", type: "noun_stem", english: "sauce", countable: true, animate: false },
    { morpheme: "cac", type: "noun_stem", english: "sandal", countable: true, animate: false},
    { morpheme: "chan", type: "noun_stem", english: "house", countable: true, animate: false },
    //{ morpheme: "a", type: "noun_stem", english: "water", countable: false, animate: false },
    { morpheme: "e", type: "noun_stem", english: "bean", countable: true, animate: false },
    { morpheme: "tepe", type: "noun_stem", english: "hill", countable: true, animate: false },
    { morpheme: "tlaca", type: "noun_stem", english: "man", english_plural: "men", countable: true, animate: true },
    { morpheme: "cihua", type: "noun_stem", english: "woman", english_plural: "women", countable: true, animate: true },
    { morpheme: "oquich", type: "noun_stem", english: "man", english_plural: "men", countable: true, animate: true },
    { morpheme: "oquichpil", type: "noun_stem", english: "boy", countable: true, animate: true },
    { morpheme: "ichpoch", type: "noun_stem", english: "girl", countable: true, animate: true },
    { morpheme: "xochi", type: "noun_stem", english: "flower", countable: true, animate: false },
    { morpheme: "coa", type: "noun_stem", english: "serpent", countable: true, animate: true },
    { morpheme: "toch", type: "noun_stem", english: "rabbit", countable: true, animate: true },
    { morpheme: "toma", type: "noun_stem", english: "tomato", english_plural: "tomatoes", countable: true, animate: false },
    { morpheme: "chil", type: "noun_stem", english: "chili", countable: true, animate: false },
    { morpheme: "cacahua", type: "noun_stem", english: "cacao", countable: false, animate: false },
    { morpheme: "comi", type: "noun_stem", english: "pot", countable: true, animate: false },
    { morpheme: "meca", type: "noun_stem", english: "rope", countable: true, animate: false },
    { morpheme: "tiyanquiz", type: "noun_stem", english: "market", countable: true, animate: false },
    { morpheme: "yollo", type: "noun_stem", english: "heart", countable: true, animate: true },
    { morpheme: "michin", type: "noun_stem", english: "fish", countable: true, animate: true },
    { morpheme: "pil", type: "noun_stem", english: "noble", countable: true, animate: true },
    { morpheme: "chichi", type: "noun_stem", english: "dog", countable: true, animate: true },

    // Suffixes
    { morpheme: "huan", type: "suffix", category: "plural" },
    { morpheme: "ca", type: "suffix", category: "locative", english_suffix: " place" },
    { morpheme: "can", type: "suffix", category: "locative", english_prefix: "place of" },
    { morpheme: "h", type: "suffix", category: "plural" },
    { morpheme: "li", type: "suffix", category: "absolutive", nominalizing: true, countable: true },
    { morpheme: "tli", type: "suffix", category: "absolutive", nominalizing: true, countable: true },
    { morpheme: "tl", type: "suffix", category: "absolutive", nominalizing: true, countable: true },
    { morpheme: "uh", type: "suffix", category: "possessive" },
    { morpheme: "ni", type: "suffix", category: "habitual", english_suffix: "er", nominalizing: true, countable: true },
    { morpheme: "liztli", type: "suffix", category: "nominalizer", english_suffix: "ing", nominalizing: true, countable: true },
    { morpheme: "yan", type: "suffix", category: "locative_of_action", english_suffix: " place where one " },
    { morpheme: "hua", type: "suffix", category: "possessive", english_suffix: " owner of " },
    { morpheme: "eh", type: "suffix", category: "possessive", english_suffix: " owner" },
    { morpheme: "tzin", type: "suffix", category: "honorific", english_prefix: "respected " },
    { morpheme: "ton", type: "suffix", category: "diminutive", english_prefix: "small " },
    { morpheme: "tin", type: "suffix", category: "plural" },
    { morpheme: "meh", type: "suffix", category: "plural" },
    { morpheme: "lli", type: "suffix", category: "participle", nominalizing: true, countable: true },
    { morpheme: "xoh", type: "suffix", category: "qualifier", english_prefix: "full of " },
    { morpheme: "yoh", type: "suffix", category: "qualifier", english_prefix: "full of " },
    { morpheme: "zoh", type: "suffix", category: "qualifier", english_prefix: "full of " },
    { morpheme: "ah", type: "suffix", category: "unspecified", english_prefix: "some" },
    { morpheme: "co", type: "suffix", category: "locative", english_prefix: "place on " },
    { morpheme: "oa", type: "suffix", category: "transitivizer", english_suffix: " to (do something)" },
    { morpheme: "lia", type: "suffix", category: "applicative", english_suffix: " for " },
    { morpheme: "tia", type: "suffix", category: "causative", english_suffix: " cause to " },
    { morpheme: "tza", type: "suffix", category: "imperfect", english_suffix: "ing" },
    { morpheme: "ya", type: "suffix", category: "imperfect", english_suffix: "ing" },
    { morpheme: "z", type: "suffix", category: "future", english_suffix: " will " },
    { morpheme: "squia", type: "suffix", category: "conditional", english_suffix: " would " },
    { morpheme: "can", type: "suffix", category: "plural" },
    { morpheme: "pan", type: "suffix", category: "locative", english_suffix: " on " },
    { morpheme: "ic", type: "suffix", category: "instrumental", english_suffix: " with " },
    { morpheme: "tzintli", type: "suffix", category: "absolutive", nominalizing: true, countable: true },
    { morpheme: "tech", type: "suffix", category: "locative", english_prefix: "next to " }
];
